-- TGDesk: seed inicial do editor admin único.
--
-- O objetivo é tirar texto livre do atendimento sem colocar preço no cliente.
-- Tudo entra sem marca e com valor zero; o servidor continua dono de custo,
-- nota fiscal, mínimos regionais e cálculo final da OS.

INSERT INTO ticket_types(key,label,icon,position) VALUES
    ('manutencao_software','Manutenção de software','terminal_outlined',20),
    ('manutencao_hardware','Manutenção de hardware','memory_outlined',30),
    ('troca_componente','Troca de componente','construction_outlined',40),
    ('rede_cabeada_wifi','Rede cabeada e Wi-Fi','settings_ethernet_outlined',50),
    ('cftv_nvr_dvr','CFTV / NVR / DVR','videocam_outlined',60),
    ('impressao_perifericos','Impressão e periféricos','print_outlined',70),
    ('energia_nobreak','Energia e nobreak','power_outlined',80),
    ('backup_dados','Backup e dados','backup_outlined',90)
ON CONFLICT (key) DO UPDATE SET
    label=excluded.label,
    icon=excluded.icon,
    position=excluded.position,
    active=true,
    updated_at=now();

INSERT INTO service_catalog(key,label,description,price_cents,duration_min,ticket_type_key,os_type,position) VALUES
    ('software_diagnostico_profundo','Diagnóstico profundo de lentidão','Coleta histórico, eventos, processos, disco, memória, GPU e reinícios.',0,90,'manutencao_software','virtual',10),
    ('software_remocao_malware','Remoção de malware e adware','Verificação, limpeza, inicialização e validação pós-reboot.',0,120,'manutencao_software','virtual',20),
    ('software_otimizacao_inicializacao','Otimização de inicialização','Serviços, programas de startup, tarefas agendadas e consumo em repouso.',0,60,'manutencao_software','virtual',30),
    ('software_reinstalacao_driver','Reinstalação ou atualização de driver','Driver de vídeo, rede, áudio, chipset, impressora ou periférico.',0,60,'manutencao_software','virtual',40),
    ('software_configuracao_backup','Configuração de backup','Rotina local, nuvem, sincronização e validação de restauração.',0,75,'backup_dados','virtual',50),
    ('hardware_diagnostico_bancada','Diagnóstico de hardware em bancada','Memória, armazenamento, fonte, temperatura, placa e periféricos.',0,120,'manutencao_hardware','onsite',60),
    ('hardware_limpeza_preventiva','Limpeza preventiva interna','Limpeza física, troca de pasta térmica quando aplicável e teste térmico.',0,90,'manutencao_hardware','onsite',70),
    ('hardware_troca_memoria','Troca ou expansão de memória RAM','Instalação, compatibilidade e teste de memória.',0,45,'troca_componente','onsite',80),
    ('hardware_troca_ssd_hd','Troca de HD/SSD','Instalação física, clonagem quando contratada e teste de saúde.',0,90,'troca_componente','onsite',90),
    ('hardware_troca_fonte','Troca de fonte de alimentação','Substituição, organização de cabos e teste de carga.',0,60,'troca_componente','onsite',100),
    ('rede_crimpagem_ponto','Crimpagem e certificação simples de ponto de rede','Conectorização, identificação e teste básico.',0,45,'rede_cabeada_wifi','onsite',110),
    ('rede_configuracao_roteador','Configuração de roteador/AP','WAN, LAN, DHCP, Wi-Fi, senha, canal e testes.',0,60,'rede_cabeada_wifi','onsite',120),
    ('rede_passagem_cabo','Passagem de cabo lógico','Metragem, identificação e acabamento simples.',0,90,'rede_cabeada_wifi','onsite',130),
    ('cftv_substituir_camera','Substituição de câmera CFTV','Troca física, ajuste de imagem e validação no DVR/NVR.',0,60,'cftv_nvr_dvr','onsite',140),
    ('cftv_configurar_nvr_dvr','Configuração de NVR/DVR','Rede, canais, gravação, horário, acesso local/remoto e teste.',0,90,'cftv_nvr_dvr','onsite',150),
    ('impressora_instalacao','Instalação/configuração de impressora','Driver, rede, compartilhamento, teste e fila.',0,60,'impressao_perifericos','virtual',160),
    ('energia_teste_nobreak','Teste de nobreak e autonomia','Bateria, carga, tomada, comunicação e relatório.',0,60,'energia_nobreak','onsite',170)
ON CONFLICT (key) DO UPDATE SET
    label=excluded.label,
    description=excluded.description,
    ticket_type_key=excluded.ticket_type_key,
    os_type=excluded.os_type,
    duration_min=excluded.duration_min,
    position=excluded.position,
    active=true,
    updated_at=now();

INSERT INTO part_catalog(sku,label,description,unit,cost_cents,price_cents,ticket_type_key,position) VALUES
    ('RAM-DDR1-DESKTOP-512MB','Memória RAM DDR1 desktop 512 MB','Módulo de memória sem marca definida.', 'un',0,0,'troca_componente',10),
    ('RAM-DDR1-DESKTOP-1GB','Memória RAM DDR1 desktop 1 GB','Módulo de memória sem marca definida.', 'un',0,0,'troca_componente',11),
    ('RAM-DDR2-DESKTOP-1GB','Memória RAM DDR2 desktop 1 GB','Módulo de memória sem marca definida.', 'un',0,0,'troca_componente',12),
    ('RAM-DDR2-DESKTOP-2GB','Memória RAM DDR2 desktop 2 GB','Módulo de memória sem marca definida.', 'un',0,0,'troca_componente',13),
    ('RAM-DDR3-DESKTOP-2GB','Memória RAM DDR3 desktop 2 GB','Módulo de memória sem marca definida.', 'un',0,0,'troca_componente',14),
    ('RAM-DDR3-DESKTOP-4GB','Memória RAM DDR3 desktop 4 GB','Módulo de memória sem marca definida.', 'un',0,0,'troca_componente',15),
    ('RAM-DDR3-DESKTOP-8GB','Memória RAM DDR3 desktop 8 GB','Módulo de memória sem marca definida.', 'un',0,0,'troca_componente',16),
    ('RAM-DDR4-DESKTOP-4GB','Memória RAM DDR4 desktop 4 GB','Módulo de memória sem marca definida.', 'un',0,0,'troca_componente',17),
    ('RAM-DDR4-DESKTOP-8GB','Memória RAM DDR4 desktop 8 GB','Módulo de memória sem marca definida.', 'un',0,0,'troca_componente',18),
    ('RAM-DDR4-DESKTOP-16GB','Memória RAM DDR4 desktop 16 GB','Módulo de memória sem marca definida.', 'un',0,0,'troca_componente',19),
    ('RAM-DDR5-DESKTOP-8GB','Memória RAM DDR5 desktop 8 GB','Módulo de memória sem marca definida.', 'un',0,0,'troca_componente',20),
    ('RAM-DDR5-DESKTOP-16GB','Memória RAM DDR5 desktop 16 GB','Módulo de memória sem marca definida.', 'un',0,0,'troca_componente',21),
    ('RAM-DDR5-DESKTOP-32GB','Memória RAM DDR5 desktop 32 GB','Módulo de memória sem marca definida.', 'un',0,0,'troca_componente',22),
    ('RAM-DDR3-NOTE-4GB','Memória RAM DDR3 notebook 4 GB','Módulo SODIMM sem marca definida.', 'un',0,0,'troca_componente',23),
    ('RAM-DDR4-NOTE-8GB','Memória RAM DDR4 notebook 8 GB','Módulo SODIMM sem marca definida.', 'un',0,0,'troca_componente',24),
    ('RAM-DDR5-NOTE-16GB','Memória RAM DDR5 notebook 16 GB','Módulo SODIMM sem marca definida.', 'un',0,0,'troca_componente',25),
    ('SSD-SATA-240GB','SSD SATA 240 GB','Unidade de armazenamento sem marca definida.', 'un',0,0,'troca_componente',30),
    ('SSD-SATA-480GB','SSD SATA 480/500 GB','Unidade de armazenamento sem marca definida.', 'un',0,0,'troca_componente',31),
    ('SSD-SATA-1TB','SSD SATA 1 TB','Unidade de armazenamento sem marca definida.', 'un',0,0,'troca_componente',32),
    ('SSD-NVME-256GB','SSD NVMe 256 GB','Unidade M.2 sem marca definida.', 'un',0,0,'troca_componente',33),
    ('SSD-NVME-512GB','SSD NVMe 512 GB','Unidade M.2 sem marca definida.', 'un',0,0,'troca_componente',34),
    ('SSD-NVME-1TB','SSD NVMe 1 TB','Unidade M.2 sem marca definida.', 'un',0,0,'troca_componente',35),
    ('HD-SATA-1TB','HD SATA 1 TB','Disco rígido sem marca definida.', 'un',0,0,'troca_componente',36),
    ('HD-SATA-2TB','HD SATA 2 TB','Disco rígido sem marca definida.', 'un',0,0,'troca_componente',37),
    ('FONTE-ATX-450W','Fonte ATX 450 W','Fonte sem marca definida.', 'un',0,0,'troca_componente',40),
    ('FONTE-ATX-500W','Fonte ATX 500 W','Fonte sem marca definida.', 'un',0,0,'troca_componente',41),
    ('FONTE-ATX-650W','Fonte ATX 650 W','Fonte sem marca definida.', 'un',0,0,'troca_componente',42),
    ('PLACA-MAE-1155','Placa-mãe LGA1155','Placa sem marca definida.', 'un',0,0,'troca_componente',50),
    ('PLACA-MAE-1200','Placa-mãe LGA1200','Placa sem marca definida.', 'un',0,0,'troca_componente',51),
    ('PLACA-MAE-AM4','Placa-mãe AM4','Placa sem marca definida.', 'un',0,0,'troca_componente',52),
    ('COOLER-CPU-UNIVERSAL','Cooler de CPU universal','Cooler sem marca definida.', 'un',0,0,'troca_componente',60),
    ('PASTA-TERMICA-G','Pasta térmica','Consumível aplicado por grama.', 'g',0,0,'manutencao_hardware',61),
    ('ALCOOL-ISOPROPILICO-ML','Álcool isopropílico','Consumível aplicado por mililitro.', 'ml',0,0,'manutencao_hardware',62),
    ('CABO-UTP-CAT5E-M','Cabo UTP Cat5e','Consumível medido por metro.', 'm',0,0,'rede_cabeada_wifi',70),
    ('CABO-UTP-CAT6-M','Cabo UTP Cat6','Consumível medido por metro.', 'm',0,0,'rede_cabeada_wifi',71),
    ('CONECTOR-RJ45','Conector RJ45','Conector sem marca definida.', 'un',0,0,'rede_cabeada_wifi',72),
    ('KEYSTONE-RJ45','Keystone RJ45','Módulo sem marca definida.', 'un',0,0,'rede_cabeada_wifi',73),
    ('PATCH-CORD-1M','Patch cord 1 m','Cabo sem marca definida.', 'un',0,0,'rede_cabeada_wifi',74),
    ('PATCH-CORD-2M','Patch cord 2 m','Cabo sem marca definida.', 'un',0,0,'rede_cabeada_wifi',75),
    ('ROTEADOR-WIFI','Roteador Wi-Fi','Equipamento fechado sem marca definida.', 'un',0,0,'rede_cabeada_wifi',76),
    ('ACCESS-POINT','Access point','Equipamento fechado sem marca definida.', 'un',0,0,'rede_cabeada_wifi',77),
    ('SWITCH-5P','Switch 5 portas','Equipamento fechado sem marca definida.', 'un',0,0,'rede_cabeada_wifi',78),
    ('SWITCH-8P','Switch 8 portas','Equipamento fechado sem marca definida.', 'un',0,0,'rede_cabeada_wifi',79),
    ('CAMERA-IP','Câmera IP','Equipamento fechado sem marca definida.', 'un',0,0,'cftv_nvr_dvr',80),
    ('CAMERA-ANALOGICA','Câmera analógica CFTV','Equipamento fechado sem marca definida.', 'un',0,0,'cftv_nvr_dvr',81),
    ('DVR-4CANAIS','DVR 4 canais','Equipamento fechado sem marca definida.', 'un',0,0,'cftv_nvr_dvr',82),
    ('DVR-8CANAIS','DVR 8 canais','Equipamento fechado sem marca definida.', 'un',0,0,'cftv_nvr_dvr',83),
    ('NVR-8CANAIS','NVR 8 canais','Equipamento fechado sem marca definida.', 'un',0,0,'cftv_nvr_dvr',84),
    ('FONTE-12V-2A','Fonte 12 V 2 A','Fonte sem marca definida.', 'un',0,0,'cftv_nvr_dvr',85),
    ('CABO-HDMI','Cabo HDMI','Cabo sem marca definida.', 'un',0,0,'troca_componente',90),
    ('CABO-VGA','Cabo VGA','Cabo sem marca definida.', 'un',0,0,'troca_componente',91),
    ('CABO-DISPLAYPORT','Cabo DisplayPort','Cabo sem marca definida.', 'un',0,0,'troca_componente',92),
    ('TECLADO-USB','Teclado USB','Periférico sem marca definida.', 'un',0,0,'impressao_perifericos',93),
    ('MOUSE-USB','Mouse USB','Periférico sem marca definida.', 'un',0,0,'impressao_perifericos',94),
    ('NOBREAK-BATERIA-12V-7AH','Bateria 12 V 7 Ah para nobreak','Bateria sem marca definida.', 'un',0,0,'energia_nobreak',100),
    ('FILTRO-LINHA','Filtro de linha','Equipamento sem marca definida.', 'un',0,0,'energia_nobreak',101)
ON CONFLICT (sku) DO UPDATE SET
    label=excluded.label,
    description=excluded.description,
    unit=excluded.unit,
    ticket_type_key=excluded.ticket_type_key,
    position=excluded.position,
    active=true,
    updated_at=now();
