-- TGDesk: expans?o do cat?logo t?cnico sem marca e sem valor.
-- Esta migra??o amplia as op??es selecion?veis; pre?o/custo continuam em zero e regras ficam no servidor.

INSERT INTO service_catalog(key,label,description,price_cents,duration_min,ticket_type_key,os_type,position) VALUES
    ('software_formatacao_windows','Formata??o e reinstala??o Windows','Backup orientado, instala??o, drivers, atualiza??es e valida??o p?s-instala??o.',0,150,'manutencao_software','virtual',1010),
    ('software_instalacao_linux','Instala??o Linux desktop','Instala??o, particionamento b?sico, drivers e atualiza??o inicial.',0,120,'manutencao_software','virtual',1020),
    ('software_dual_boot','Configura??o dual boot','Particionamento, bootloader e valida??o dos sistemas instalados.',0,150,'manutencao_software','virtual',1030),
    ('software_migracao_perfil','Migra??o de perfil de usu?rio','Copia documentos, ?rea de trabalho, favoritos e configura??es compat?veis.',0,120,'manutencao_software','virtual',1040),
    ('software_recuperacao_sistema','Recupera??o de inicializa??o do sistema','Reparo de boot, restaura??o, arquivos corrompidos e valida??o p?s-reboot.',0,120,'manutencao_software','virtual',1050),
    ('software_limpeza_temporarios','Limpeza t?cnica de tempor?rios e cache','Remove arquivos tempor?rios, caches e res?duos sem apagar dados do cliente.',0,45,'manutencao_software','virtual',1060),
    ('software_office_email','Configura??o de Office/e-mail','Conta, assinatura, cliente de e-mail, perfil e teste de envio/recebimento.',0,60,'manutencao_software','virtual',1070),
    ('software_antivirus_edr','Instala??o/configura??o antiv?rus ou EDR','Instala agente, pol?tica b?sica, varredura inicial e valida??o de prote??o.',0,75,'manutencao_software','virtual',1080),
    ('software_atualizacao_bios','Atualiza??o BIOS/UEFI','Valida modelo, energia, vers?o e executa atualiza??o assistida.',0,90,'manutencao_software','virtual',1090),
    ('software_virtualizacao','Configura??o de virtualiza??o','Hyper-V, VirtualBox, VMware, recursos de BIOS e teste de VM.',0,90,'manutencao_software','virtual',1100),
    ('software_vpn_acesso_remoto','Configura??o VPN/acesso remoto','Cliente VPN, credenciais, rota, MFA e teste de conex?o.',0,75,'manutencao_software','virtual',1110),
    ('software_erp_certificado','Configura??o ERP/certificado digital','Instala certificados, cadeias, tokens, leitores e valida acesso ao sistema.',0,90,'manutencao_software','virtual',1120),
    ('hardware_montagem_pc','Montagem de computador completo','Montagem f?sica, organiza??o de cabos, BIOS, teste t?rmico e boot inicial.',0,180,'manutencao_hardware','onsite',1130),
    ('hardware_upgrade_pc','Upgrade de computador','Troca/adi??o de componente, compatibilidade e testes ap?s instala??o.',0,120,'manutencao_hardware','onsite',1140),
    ('hardware_troca_placa_mae','Troca de placa-m?e','Desmontagem, instala??o, reconex?o, BIOS e valida??o de perif?ricos.',0,150,'manutencao_hardware','onsite',1150),
    ('hardware_troca_processador','Troca de processador','Instala CPU, cooler, pasta t?rmica, BIOS e teste de temperatura.',0,120,'manutencao_hardware','onsite',1160),
    ('hardware_troca_cooler','Troca de cooler/ventoinha','Substitui cooler, fan ou dissipa??o e valida ru?do/temperatura.',0,75,'manutencao_hardware','onsite',1170),
    ('hardware_troca_tela_note','Troca de tela de notebook','Substitui??o de painel compat?vel e teste de imagem.',0,120,'manutencao_hardware','onsite',1180),
    ('hardware_troca_teclado_note','Troca de teclado de notebook','Substitui??o, encaixes, flat cable e teste de teclas.',0,90,'manutencao_hardware','onsite',1190),
    ('hardware_troca_bateria_note','Troca de bateria de notebook','Substitui??o, calibra??o inicial e teste de carga.',0,60,'manutencao_hardware','onsite',1200),
    ('hardware_reparo_conector_dc','Troca/reparo conector DC jack','Substitui conector de carga e valida alimenta??o.',0,120,'manutencao_hardware','onsite',1210),
    ('hardware_diagnostico_intermitencia','Diagn?stico de falha intermitente','Observa??o prolongada, logs, temperatura, energia e stress controlado.',0,180,'manutencao_hardware','onsite',1220),
    ('rede_site_survey_wifi','Site survey Wi-Fi b?sico','Mapeia sinal, interfer?ncia, posicionamento e recomenda AP/canais.',0,120,'rede_cabeada_wifi','onsite',1230),
    ('rede_instalacao_rack','Organiza??o/instala??o de rack','Instala patch panel, switch, identifica??o e organiza??o b?sica.',0,180,'rede_cabeada_wifi','onsite',1240),
    ('rede_patch_panel','Montagem de patch panel','Termina??o, identifica??o e teste de pontos.',0,150,'rede_cabeada_wifi','onsite',1250),
    ('rede_vlan_basica','Configura??o VLAN b?sica','Cria VLANs, portas access/trunk e teste entre segmentos.',0,120,'rede_cabeada_wifi','onsite',1260),
    ('rede_firewall_basico','Configura??o firewall b?sico','Regras de acesso, NAT, DHCP, DNS e teste de conectividade.',0,120,'rede_cabeada_wifi','onsite',1270),
    ('rede_ponto_adicional','Instala??o de ponto de rede adicional','Passagem, termina??o, identifica??o e teste do ponto.',0,120,'rede_cabeada_wifi','onsite',1280),
    ('rede_mesh_wifi','Instala??o de rede mesh','Configura n?s, backhaul, roaming e teste de cobertura.',0,120,'rede_cabeada_wifi','onsite',1290),
    ('cftv_instalacao_camera','Instala??o de c?mera CFTV','Fixa??o, passagem de cabo, conectoriza??o, imagem e grava??o.',0,120,'cftv_nvr_dvr','onsite',1300),
    ('cftv_instalacao_dvr_nvr','Instala??o de DVR/NVR','Instala gravador, disco, rede, canais e teste de grava??o.',0,150,'cftv_nvr_dvr','onsite',1310),
    ('cftv_acesso_remoto','Configura??o de acesso remoto CFTV','App, nuvem/P2P, portas quando aplic?vel e teste externo.',0,90,'cftv_nvr_dvr','onsite',1320),
    ('cftv_manutencao_imagem','Corre??o de imagem/interfer?ncia CFTV','Verifica alimenta??o, conectores, cabo, c?mera e canal.',0,90,'cftv_nvr_dvr','onsite',1330),
    ('cftv_troca_hd_gravador','Troca de HD de DVR/NVR','Instala disco, inicializa, configura grava??o e valida sa?de.',0,75,'cftv_nvr_dvr','onsite',1340),
    ('impressora_manutencao_fila','Corre??o de fila/spooler de impress?o','Limpa fila, reinstala driver e valida impress?o.',0,60,'impressao_perifericos','virtual',1350),
    ('impressora_rede_scan','Configura??o scanner em rede','SMB, e-mail, pasta, driver e teste de digitaliza??o.',0,90,'impressao_perifericos','virtual',1360),
    ('periferico_instalacao_webcam','Instala??o de webcam/microfone/headset','Driver, permiss?es, app de reuni?o e teste de ?udio/v?deo.',0,45,'impressao_perifericos','virtual',1370),
    ('dados_clonagem_disco','Clonagem de disco','Clona armazenamento, ajusta boot e valida inicializa??o.',0,120,'impressao_perifericos','virtual',1380),
    ('dados_recuperacao_basica','Recupera??o b?sica de dados','Tentativa l?gica em m?dia acess?vel, c?pia e relat?rio de arquivos.',0,180,'impressao_perifericos','virtual',1390),
    ('energia_troca_bateria_nobreak','Troca de bateria de nobreak','Substitui bateria, testa carga/autonomia e descarte orientado.',0,75,'energia_nobreak','onsite',1400),
    ('energia_diagnostico_tomada','Diagn?stico b?sico de tomada/energia','Verifica aterramento aparente, tens?o, filtro, nobreak e riscos vis?veis.',0,60,'energia_nobreak','onsite',1410)
ON CONFLICT (key) DO UPDATE SET
    label=excluded.label,
    description=excluded.description,
    ticket_type_key=excluded.ticket_type_key,
    os_type=excluded.os_type,
    duration_min=excluded.duration_min,
    position=excluded.position,
    active=true,
    updated_at=now();

INSERT INTO part_catalog(sku,label,description,unit,cost_cents,price_cents,ticket_type_key,position,item_kind,requires_invoice_photo) VALUES
    ('RAM-DDR1-DESKTOP-256MB','Mem?ria RAM DDR1 desktop DIMM 256MB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1001,'part',true),
    ('RAM-DDR1-DESKTOP-512MB','Mem?ria RAM DDR1 desktop DIMM 512MB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1002,'part',true),
    ('RAM-DDR1-DESKTOP-1GB','Mem?ria RAM DDR1 desktop DIMM 1GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1003,'part',true),
    ('RAM-DDR1-NOTE-256MB','Mem?ria RAM DDR1 notebook SODIMM 256MB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1004,'part',true),
    ('RAM-DDR1-NOTE-512MB','Mem?ria RAM DDR1 notebook SODIMM 512MB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1005,'part',true),
    ('RAM-DDR1-NOTE-1GB','Mem?ria RAM DDR1 notebook SODIMM 1GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1006,'part',true),
    ('RAM-DDR2-DESKTOP-512MB','Mem?ria RAM DDR2 desktop DIMM 512MB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1007,'part',true),
    ('RAM-DDR2-DESKTOP-1GB','Mem?ria RAM DDR2 desktop DIMM 1GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1008,'part',true),
    ('RAM-DDR2-DESKTOP-2GB','Mem?ria RAM DDR2 desktop DIMM 2GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1009,'part',true),
    ('RAM-DDR2-DESKTOP-4GB','Mem?ria RAM DDR2 desktop DIMM 4GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1010,'part',true),
    ('RAM-DDR2-NOTE-512MB','Mem?ria RAM DDR2 notebook SODIMM 512MB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1011,'part',true),
    ('RAM-DDR2-NOTE-1GB','Mem?ria RAM DDR2 notebook SODIMM 1GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1012,'part',true),
    ('RAM-DDR2-NOTE-2GB','Mem?ria RAM DDR2 notebook SODIMM 2GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1013,'part',true),
    ('RAM-DDR2-NOTE-4GB','Mem?ria RAM DDR2 notebook SODIMM 4GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1014,'part',true),
    ('RAM-DDR3-DESKTOP-1GB','Mem?ria RAM DDR3 desktop DIMM 1GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1015,'part',true),
    ('RAM-DDR3-DESKTOP-2GB','Mem?ria RAM DDR3 desktop DIMM 2GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1016,'part',true),
    ('RAM-DDR3-DESKTOP-4GB','Mem?ria RAM DDR3 desktop DIMM 4GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1017,'part',true),
    ('RAM-DDR3-DESKTOP-8GB','Mem?ria RAM DDR3 desktop DIMM 8GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1018,'part',true),
    ('RAM-DDR3-DESKTOP-16GB','Mem?ria RAM DDR3 desktop DIMM 16GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1019,'part',true),
    ('RAM-DDR3-NOTE-1GB','Mem?ria RAM DDR3 notebook SODIMM 1GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1020,'part',true),
    ('RAM-DDR3-NOTE-2GB','Mem?ria RAM DDR3 notebook SODIMM 2GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1021,'part',true),
    ('RAM-DDR3-NOTE-4GB','Mem?ria RAM DDR3 notebook SODIMM 4GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1022,'part',true),
    ('RAM-DDR3-NOTE-8GB','Mem?ria RAM DDR3 notebook SODIMM 8GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1023,'part',true),
    ('RAM-DDR3-NOTE-16GB','Mem?ria RAM DDR3 notebook SODIMM 16GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1024,'part',true),
    ('RAM-DDR4-DESKTOP-4GB','Mem?ria RAM DDR4 desktop DIMM 4GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1025,'part',true),
    ('RAM-DDR4-DESKTOP-8GB','Mem?ria RAM DDR4 desktop DIMM 8GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1026,'part',true),
    ('RAM-DDR4-DESKTOP-16GB','Mem?ria RAM DDR4 desktop DIMM 16GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1027,'part',true),
    ('RAM-DDR4-DESKTOP-32GB','Mem?ria RAM DDR4 desktop DIMM 32GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1028,'part',true),
    ('RAM-DDR4-DESKTOP-64GB','Mem?ria RAM DDR4 desktop DIMM 64GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1029,'part',true),
    ('RAM-DDR4-NOTE-4GB','Mem?ria RAM DDR4 notebook SODIMM 4GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1030,'part',true),
    ('RAM-DDR4-NOTE-8GB','Mem?ria RAM DDR4 notebook SODIMM 8GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1031,'part',true),
    ('RAM-DDR4-NOTE-16GB','Mem?ria RAM DDR4 notebook SODIMM 16GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1032,'part',true),
    ('RAM-DDR4-NOTE-32GB','Mem?ria RAM DDR4 notebook SODIMM 32GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1033,'part',true),
    ('RAM-DDR4-NOTE-64GB','Mem?ria RAM DDR4 notebook SODIMM 64GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1034,'part',true),
    ('RAM-DDR5-DESKTOP-8GB','Mem?ria RAM DDR5 desktop DIMM 8GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1035,'part',true),
    ('RAM-DDR5-DESKTOP-16GB','Mem?ria RAM DDR5 desktop DIMM 16GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1036,'part',true),
    ('RAM-DDR5-DESKTOP-32GB','Mem?ria RAM DDR5 desktop DIMM 32GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1037,'part',true),
    ('RAM-DDR5-DESKTOP-64GB','Mem?ria RAM DDR5 desktop DIMM 64GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1038,'part',true),
    ('RAM-DDR5-NOTE-8GB','Mem?ria RAM DDR5 notebook SODIMM 8GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1039,'part',true),
    ('RAM-DDR5-NOTE-16GB','Mem?ria RAM DDR5 notebook SODIMM 16GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1040,'part',true),
    ('RAM-DDR5-NOTE-32GB','Mem?ria RAM DDR5 notebook SODIMM 32GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1041,'part',true),
    ('RAM-DDR5-NOTE-64GB','Mem?ria RAM DDR5 notebook SODIMM 64GB','M?dulo de mem?ria sem marca definida, especifica??o validada pelo t?cnico.','un',0,0,'troca_componente',1042,'part',true),
    ('SSD-SATA-120GB','SSD SATA 2,5 pol 120GB','Unidade de armazenamento sem marca definida.','un',0,0,'troca_componente',1043,'part',true),
    ('SSD-SATA-240GB','SSD SATA 2,5 pol 240GB','Unidade de armazenamento sem marca definida.','un',0,0,'troca_componente',1044,'part',true),
    ('SSD-SATA-480GB','SSD SATA 2,5 pol 480GB','Unidade de armazenamento sem marca definida.','un',0,0,'troca_componente',1045,'part',true),
    ('SSD-SATA-500GB','SSD SATA 2,5 pol 500GB','Unidade de armazenamento sem marca definida.','un',0,0,'troca_componente',1046,'part',true),
    ('SSD-SATA-960GB','SSD SATA 2,5 pol 960GB','Unidade de armazenamento sem marca definida.','un',0,0,'troca_componente',1047,'part',true),
    ('SSD-SATA-1TB','SSD SATA 2,5 pol 1TB','Unidade de armazenamento sem marca definida.','un',0,0,'troca_componente',1048,'part',true),
    ('SSD-SATA-2TB','SSD SATA 2,5 pol 2TB','Unidade de armazenamento sem marca definida.','un',0,0,'troca_componente',1049,'part',true),
    ('SSD-SATA-4TB','SSD SATA 2,5 pol 4TB','Unidade de armazenamento sem marca definida.','un',0,0,'troca_componente',1050,'part',true),
    ('SSD-NVME-128GB','SSD NVMe M.2 128GB','Unidade de armazenamento sem marca definida.','un',0,0,'troca_componente',1051,'part',true),
    ('SSD-NVME-256GB','SSD NVMe M.2 256GB','Unidade de armazenamento sem marca definida.','un',0,0,'troca_componente',1052,'part',true),
    ('SSD-NVME-512GB','SSD NVMe M.2 512GB','Unidade de armazenamento sem marca definida.','un',0,0,'troca_componente',1053,'part',true),
    ('SSD-NVME-1TB','SSD NVMe M.2 1TB','Unidade de armazenamento sem marca definida.','un',0,0,'troca_componente',1054,'part',true),
    ('SSD-NVME-2TB','SSD NVMe M.2 2TB','Unidade de armazenamento sem marca definida.','un',0,0,'troca_componente',1055,'part',true),
    ('SSD-NVME-4TB','SSD NVMe M.2 4TB','Unidade de armazenamento sem marca definida.','un',0,0,'troca_componente',1056,'part',true),
    ('SSD-MSATA-128GB','SSD mSATA 128GB','Unidade de armazenamento sem marca definida.','un',0,0,'troca_componente',1057,'part',true),
    ('SSD-MSATA-256GB','SSD mSATA 256GB','Unidade de armazenamento sem marca definida.','un',0,0,'troca_componente',1058,'part',true),
    ('SSD-MSATA-512GB','SSD mSATA 512GB','Unidade de armazenamento sem marca definida.','un',0,0,'troca_componente',1059,'part',true),
    ('SSD-MSATA-1TB','SSD mSATA 1TB','Unidade de armazenamento sem marca definida.','un',0,0,'troca_componente',1060,'part',true),
    ('HD-SATA-35-500GB','HD SATA 3,5 pol 500GB','Unidade de armazenamento sem marca definida.','un',0,0,'troca_componente',1061,'part',true),
    ('HD-SATA-35-1TB','HD SATA 3,5 pol 1TB','Unidade de armazenamento sem marca definida.','un',0,0,'troca_componente',1062,'part',true),
    ('HD-SATA-35-2TB','HD SATA 3,5 pol 2TB','Unidade de armazenamento sem marca definida.','un',0,0,'troca_componente',1063,'part',true),
    ('HD-SATA-35-4TB','HD SATA 3,5 pol 4TB','Unidade de armazenamento sem marca definida.','un',0,0,'troca_componente',1064,'part',true),
    ('HD-SATA-35-6TB','HD SATA 3,5 pol 6TB','Unidade de armazenamento sem marca definida.','un',0,0,'troca_componente',1065,'part',true),
    ('HD-SATA-35-8TB','HD SATA 3,5 pol 8TB','Unidade de armazenamento sem marca definida.','un',0,0,'troca_componente',1066,'part',true),
    ('HD-SATA-35-10TB','HD SATA 3,5 pol 10TB','Unidade de armazenamento sem marca definida.','un',0,0,'troca_componente',1067,'part',true),
    ('HD-SATA-25-320GB','HD SATA 2,5 pol 320GB','Unidade de armazenamento sem marca definida.','un',0,0,'troca_componente',1068,'part',true),
    ('HD-SATA-25-500GB','HD SATA 2,5 pol 500GB','Unidade de armazenamento sem marca definida.','un',0,0,'troca_componente',1069,'part',true),
    ('HD-SATA-25-1TB','HD SATA 2,5 pol 1TB','Unidade de armazenamento sem marca definida.','un',0,0,'troca_componente',1070,'part',true),
    ('HD-SATA-25-2TB','HD SATA 2,5 pol 2TB','Unidade de armazenamento sem marca definida.','un',0,0,'troca_componente',1071,'part',true),
    ('HD-CFTV-1TB','HD para CFTV/DVR/NVR 1TB','Unidade de armazenamento sem marca definida.','un',0,0,'cftv_nvr_dvr',1072,'part',true),
    ('HD-CFTV-2TB','HD para CFTV/DVR/NVR 2TB','Unidade de armazenamento sem marca definida.','un',0,0,'cftv_nvr_dvr',1073,'part',true),
    ('HD-CFTV-4TB','HD para CFTV/DVR/NVR 4TB','Unidade de armazenamento sem marca definida.','un',0,0,'cftv_nvr_dvr',1074,'part',true),
    ('HD-CFTV-6TB','HD para CFTV/DVR/NVR 6TB','Unidade de armazenamento sem marca definida.','un',0,0,'cftv_nvr_dvr',1075,'part',true),
    ('HD-CFTV-8TB','HD para CFTV/DVR/NVR 8TB','Unidade de armazenamento sem marca definida.','un',0,0,'cftv_nvr_dvr',1076,'part',true),
    ('HD-CFTV-10TB','HD para CFTV/DVR/NVR 10TB','Unidade de armazenamento sem marca definida.','un',0,0,'cftv_nvr_dvr',1077,'part',true),
    ('FONTE-ATX-300W','Fonte ATX 300W','Fonte de alimenta??o sem marca definida.','un',0,0,'troca_componente',1078,'part',true),
    ('FONTE-ATX-350W','Fonte ATX 350W','Fonte de alimenta??o sem marca definida.','un',0,0,'troca_componente',1079,'part',true),
    ('FONTE-ATX-400W','Fonte ATX 400W','Fonte de alimenta??o sem marca definida.','un',0,0,'troca_componente',1080,'part',true),
    ('FONTE-ATX-450W','Fonte ATX 450W','Fonte de alimenta??o sem marca definida.','un',0,0,'troca_componente',1081,'part',true),
    ('FONTE-ATX-500W','Fonte ATX 500W','Fonte de alimenta??o sem marca definida.','un',0,0,'troca_componente',1082,'part',true),
    ('FONTE-ATX-550W','Fonte ATX 550W','Fonte de alimenta??o sem marca definida.','un',0,0,'troca_componente',1083,'part',true),
    ('FONTE-ATX-600W','Fonte ATX 600W','Fonte de alimenta??o sem marca definida.','un',0,0,'troca_componente',1084,'part',true),
    ('FONTE-ATX-650W','Fonte ATX 650W','Fonte de alimenta??o sem marca definida.','un',0,0,'troca_componente',1085,'part',true),
    ('FONTE-ATX-750W','Fonte ATX 750W','Fonte de alimenta??o sem marca definida.','un',0,0,'troca_componente',1086,'part',true),
    ('FONTE-ATX-850W','Fonte ATX 850W','Fonte de alimenta??o sem marca definida.','un',0,0,'troca_componente',1087,'part',true),
    ('PLACA-MAE-775','Placa-m?e socket 775','Placa-m?e sem marca definida.','un',0,0,'troca_componente',1088,'part',true),
    ('PLACA-MAE-1155','Placa-m?e socket 1155','Placa-m?e sem marca definida.','un',0,0,'troca_componente',1089,'part',true),
    ('PLACA-MAE-1156','Placa-m?e socket 1156','Placa-m?e sem marca definida.','un',0,0,'troca_componente',1090,'part',true),
    ('PLACA-MAE-1150','Placa-m?e socket 1150','Placa-m?e sem marca definida.','un',0,0,'troca_componente',1091,'part',true),
    ('PLACA-MAE-1151','Placa-m?e socket 1151','Placa-m?e sem marca definida.','un',0,0,'troca_componente',1092,'part',true),
    ('PLACA-MAE-1200','Placa-m?e socket 1200','Placa-m?e sem marca definida.','un',0,0,'troca_componente',1093,'part',true),
    ('PLACA-MAE-1700','Placa-m?e socket 1700','Placa-m?e sem marca definida.','un',0,0,'troca_componente',1094,'part',true),
    ('PLACA-MAE-AM3','Placa-m?e socket AM3','Placa-m?e sem marca definida.','un',0,0,'troca_componente',1095,'part',true),
    ('PLACA-MAE-AM4','Placa-m?e socket AM4','Placa-m?e sem marca definida.','un',0,0,'troca_componente',1096,'part',true),
    ('PLACA-MAE-AM5','Placa-m?e socket AM5','Placa-m?e sem marca definida.','un',0,0,'troca_componente',1097,'part',true),
    ('COOLER-CPU-BOX','Cooler cpu box','Cooler/ventoinha sem marca definida.','un',0,0,'troca_componente',1098,'part',true),
    ('COOLER-CPU-TORRE','Cooler cpu torre','Cooler/ventoinha sem marca definida.','un',0,0,'troca_componente',1099,'part',true),
    ('COOLER-NOTEBOOK','Cooler notebook','Cooler/ventoinha sem marca definida.','un',0,0,'troca_componente',1100,'part',true),
    ('COOLER-GABINETE-80MM','Cooler gabinete 80mm','Cooler/ventoinha sem marca definida.','un',0,0,'troca_componente',1101,'part',true),
    ('COOLER-GABINETE-120MM','Cooler gabinete 120mm','Cooler/ventoinha sem marca definida.','un',0,0,'troca_componente',1102,'part',true),
    ('COOLER-GABINETE-140MM','Cooler gabinete 140mm','Cooler/ventoinha sem marca definida.','un',0,0,'troca_componente',1103,'part',true),
    ('GPU-PCIE-BASICA','Placa de v?deo PCIe b?sica','Componente sem marca definida.','un',0,0,'troca_componente',1104,'part',true),
    ('GPU-PCIE-INTERMEDIARIA','Placa de v?deo PCIe intermedi?ria','Componente sem marca definida.','un',0,0,'troca_componente',1105,'part',true),
    ('PLACA-REDE-PCIE','Placa de rede PCIe','Componente sem marca definida.','un',0,0,'troca_componente',1106,'part',true),
    ('PLACA-WIFI-PCIE','Placa Wi-Fi PCIe','Componente sem marca definida.','un',0,0,'troca_componente',1107,'part',true),
    ('ADAPTADOR-WIFI-USB','Adaptador Wi-Fi USB','Componente sem marca definida.','un',0,0,'troca_componente',1108,'part',true),
    ('GABINETE-ATX','Gabinete ATX','Componente sem marca definida.','un',0,0,'troca_componente',1109,'part',true),
    ('GABINETE-MATX','Gabinete micro ATX','Componente sem marca definida.','un',0,0,'troca_componente',1110,'part',true),
    ('TELA-NOTE-116','Tela notebook 11,6 pol','Pe?a de notebook sem marca definida.','un',0,0,'troca_componente',1111,'part',true),
    ('TELA-NOTE-133','Tela notebook 13,3 pol','Pe?a de notebook sem marca definida.','un',0,0,'troca_componente',1112,'part',true),
    ('TELA-NOTE-140','Tela notebook 14 pol','Pe?a de notebook sem marca definida.','un',0,0,'troca_componente',1113,'part',true),
    ('TELA-NOTE-156','Tela notebook 15,6 pol','Pe?a de notebook sem marca definida.','un',0,0,'troca_componente',1114,'part',true),
    ('TELA-NOTE-173','Tela notebook 17,3 pol','Pe?a de notebook sem marca definida.','un',0,0,'troca_componente',1115,'part',true),
    ('TECLADO-NOTE-ABNT2','Teclado notebook ABNT2','Pe?a de notebook sem marca definida.','un',0,0,'troca_componente',1116,'part',true),
    ('BATERIA-NOTE','Bateria notebook','Pe?a de notebook sem marca definida.','un',0,0,'troca_componente',1117,'part',true),
    ('FONTE-NOTE-45W','Fonte notebook 45 W','Pe?a de notebook sem marca definida.','un',0,0,'troca_componente',1118,'part',true),
    ('FONTE-NOTE-65W','Fonte notebook 65 W','Pe?a de notebook sem marca definida.','un',0,0,'troca_componente',1119,'part',true),
    ('FONTE-NOTE-90W','Fonte notebook 90 W','Pe?a de notebook sem marca definida.','un',0,0,'troca_componente',1120,'part',true),
    ('DC-JACK-NOTE','Conector DC jack notebook','Pe?a de notebook sem marca definida.','un',0,0,'troca_componente',1121,'part',true),
    ('FLAT-TELA-NOTE','Cabo flat de tela notebook','Pe?a de notebook sem marca definida.','un',0,0,'troca_componente',1122,'part',true),
    ('CABO-UTP-CAT5E-M','Cabo UTP CAT5E por metro','Consum?vel medido por metro, sem marca definida.','m',0,0,'rede_cabeada_wifi',1123,'consumable',true),
    ('PATCH-CORD-CAT5E-1M','Patch cord CAT5E 1 m','Cabo pronto sem marca definida.','un',0,0,'rede_cabeada_wifi',1124,'part',true),
    ('PATCH-CORD-CAT5E-2M','Patch cord CAT5E 2 m','Cabo pronto sem marca definida.','un',0,0,'rede_cabeada_wifi',1125,'part',true),
    ('PATCH-CORD-CAT5E-3M','Patch cord CAT5E 3 m','Cabo pronto sem marca definida.','un',0,0,'rede_cabeada_wifi',1126,'part',true),
    ('CABO-UTP-CAT6-M','Cabo UTP CAT6 por metro','Consum?vel medido por metro, sem marca definida.','m',0,0,'rede_cabeada_wifi',1127,'consumable',true),
    ('PATCH-CORD-CAT6-1M','Patch cord CAT6 1 m','Cabo pronto sem marca definida.','un',0,0,'rede_cabeada_wifi',1128,'part',true),
    ('PATCH-CORD-CAT6-2M','Patch cord CAT6 2 m','Cabo pronto sem marca definida.','un',0,0,'rede_cabeada_wifi',1129,'part',true),
    ('PATCH-CORD-CAT6-3M','Patch cord CAT6 3 m','Cabo pronto sem marca definida.','un',0,0,'rede_cabeada_wifi',1130,'part',true),
    ('CABO-UTP-CAT6A-M','Cabo UTP CAT6A por metro','Consum?vel medido por metro, sem marca definida.','m',0,0,'rede_cabeada_wifi',1131,'consumable',true),
    ('PATCH-CORD-CAT6A-1M','Patch cord CAT6A 1 m','Cabo pronto sem marca definida.','un',0,0,'rede_cabeada_wifi',1132,'part',true),
    ('PATCH-CORD-CAT6A-2M','Patch cord CAT6A 2 m','Cabo pronto sem marca definida.','un',0,0,'rede_cabeada_wifi',1133,'part',true),
    ('PATCH-CORD-CAT6A-3M','Patch cord CAT6A 3 m','Cabo pronto sem marca definida.','un',0,0,'rede_cabeada_wifi',1134,'part',true),
    ('CONECTOR-RJ45-CAT5E','Conector RJ45 Cat5e','Item de rede sem marca definida.','un',0,0,'rede_cabeada_wifi',1135,'consumable',true),
    ('CONECTOR-RJ45-CAT6','Conector RJ45 Cat6','Item de rede sem marca definida.','un',0,0,'rede_cabeada_wifi',1136,'consumable',true),
    ('CAPA-RJ45','Capa para conector RJ45','Item de rede sem marca definida.','un',0,0,'rede_cabeada_wifi',1137,'consumable',true),
    ('KEYSTONE-RJ45-CAT5E','Keystone RJ45 Cat5e','Item de rede sem marca definida.','un',0,0,'rede_cabeada_wifi',1138,'part',true),
    ('KEYSTONE-RJ45-CAT6','Keystone RJ45 Cat6','Item de rede sem marca definida.','un',0,0,'rede_cabeada_wifi',1139,'part',true),
    ('ESPELHO-RJ45-1P','Espelho RJ45 1 porta','Item de rede sem marca definida.','un',0,0,'rede_cabeada_wifi',1140,'part',true),
    ('ESPELHO-RJ45-2P','Espelho RJ45 2 portas','Item de rede sem marca definida.','un',0,0,'rede_cabeada_wifi',1141,'part',true),
    ('PATCH-PANEL-24P','Patch panel 24 portas','Item de rede sem marca definida.','un',0,0,'rede_cabeada_wifi',1142,'part',true),
    ('RACK-PAREDE-6U','Rack parede 6U','Item de rede sem marca definida.','un',0,0,'rede_cabeada_wifi',1143,'part',true),
    ('RACK-PAREDE-8U','Rack parede 8U','Item de rede sem marca definida.','un',0,0,'rede_cabeada_wifi',1144,'part',true),
    ('ORGANIZADOR-CABO-1U','Organizador de cabos 1U','Item de rede sem marca definida.','un',0,0,'rede_cabeada_wifi',1145,'part',true),
    ('ABRACADEIRA-NYLON','Abra?adeira nylon','Item de rede sem marca definida.','un',0,0,'rede_cabeada_wifi',1146,'consumable',true),
    ('FITA-ISOLANTE-M','Fita isolante por metro','Item de rede sem marca definida.','m',0,0,'rede_cabeada_wifi',1147,'consumable',true),
    ('CANALETA-M','Canaleta por metro','Item de rede sem marca definida.','m',0,0,'rede_cabeada_wifi',1148,'consumable',true),
    ('SWITCH-5P','Switch 5 portas','Switch sem marca definida.','un',0,0,'rede_cabeada_wifi',1149,'part',true),
    ('SWITCH-POE-5P','Switch PoE 5 portas','Switch PoE sem marca definida.','un',0,0,'rede_cabeada_wifi',1150,'part',true),
    ('SWITCH-8P','Switch 8 portas','Switch sem marca definida.','un',0,0,'rede_cabeada_wifi',1151,'part',true),
    ('SWITCH-POE-8P','Switch PoE 8 portas','Switch PoE sem marca definida.','un',0,0,'rede_cabeada_wifi',1152,'part',true),
    ('SWITCH-16P','Switch 16 portas','Switch sem marca definida.','un',0,0,'rede_cabeada_wifi',1153,'part',true),
    ('SWITCH-POE-16P','Switch PoE 16 portas','Switch PoE sem marca definida.','un',0,0,'rede_cabeada_wifi',1154,'part',true),
    ('SWITCH-24P','Switch 24 portas','Switch sem marca definida.','un',0,0,'rede_cabeada_wifi',1155,'part',true),
    ('SWITCH-POE-24P','Switch PoE 24 portas','Switch PoE sem marca definida.','un',0,0,'rede_cabeada_wifi',1156,'part',true),
    ('SWITCH-48P','Switch 48 portas','Switch sem marca definida.','un',0,0,'rede_cabeada_wifi',1157,'part',true),
    ('SWITCH-POE-48P','Switch PoE 48 portas','Switch PoE sem marca definida.','un',0,0,'rede_cabeada_wifi',1158,'part',true),
    ('ROTEADOR-WIFI4','Roteador Wi-Fi 4','Equipamento de rede sem marca definida.','un',0,0,'rede_cabeada_wifi',1159,'part',true),
    ('ROTEADOR-WIFI5','Roteador Wi-Fi 5','Equipamento de rede sem marca definida.','un',0,0,'rede_cabeada_wifi',1160,'part',true),
    ('ROTEADOR-WIFI6','Roteador Wi-Fi 6','Equipamento de rede sem marca definida.','un',0,0,'rede_cabeada_wifi',1161,'part',true),
    ('ACCESS-POINT-TETO','Access point de teto','Equipamento de rede sem marca definida.','un',0,0,'rede_cabeada_wifi',1162,'part',true),
    ('ACCESS-POINT-PAREDE','Access point de parede','Equipamento de rede sem marca definida.','un',0,0,'rede_cabeada_wifi',1163,'part',true),
    ('MESH-2NOS','Kit mesh 2 n?s','Equipamento de rede sem marca definida.','un',0,0,'rede_cabeada_wifi',1164,'part',true),
    ('MESH-3NOS','Kit mesh 3 n?s','Equipamento de rede sem marca definida.','un',0,0,'rede_cabeada_wifi',1165,'part',true),
    ('FIREWALL-SOHO','Firewall/roteador SOHO','Equipamento de rede sem marca definida.','un',0,0,'rede_cabeada_wifi',1166,'part',true),
    ('CAMERA-ANALOGICA-BULLET-720P','C?mera ANALOGICA bullet 720P','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1167,'part',true),
    ('CAMERA-ANALOGICA-BULLET-1080P','C?mera ANALOGICA bullet 1080P','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1168,'part',true),
    ('CAMERA-ANALOGICA-BULLET-4MP','C?mera ANALOGICA bullet 4MP','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1169,'part',true),
    ('CAMERA-ANALOGICA-BULLET-5MP','C?mera ANALOGICA bullet 5MP','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1170,'part',true),
    ('CAMERA-ANALOGICA-BULLET-8MP','C?mera ANALOGICA bullet 8MP','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1171,'part',true),
    ('CAMERA-ANALOGICA-DOME-720P','C?mera ANALOGICA dome 720P','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1172,'part',true),
    ('CAMERA-ANALOGICA-DOME-1080P','C?mera ANALOGICA dome 1080P','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1173,'part',true),
    ('CAMERA-ANALOGICA-DOME-4MP','C?mera ANALOGICA dome 4MP','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1174,'part',true),
    ('CAMERA-ANALOGICA-DOME-5MP','C?mera ANALOGICA dome 5MP','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1175,'part',true),
    ('CAMERA-ANALOGICA-DOME-8MP','C?mera ANALOGICA dome 8MP','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1176,'part',true),
    ('CAMERA-AHD-BULLET-720P','C?mera AHD bullet 720P','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1177,'part',true),
    ('CAMERA-AHD-BULLET-1080P','C?mera AHD bullet 1080P','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1178,'part',true),
    ('CAMERA-AHD-BULLET-4MP','C?mera AHD bullet 4MP','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1179,'part',true),
    ('CAMERA-AHD-BULLET-5MP','C?mera AHD bullet 5MP','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1180,'part',true),
    ('CAMERA-AHD-BULLET-8MP','C?mera AHD bullet 8MP','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1181,'part',true),
    ('CAMERA-AHD-DOME-720P','C?mera AHD dome 720P','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1182,'part',true),
    ('CAMERA-AHD-DOME-1080P','C?mera AHD dome 1080P','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1183,'part',true),
    ('CAMERA-AHD-DOME-4MP','C?mera AHD dome 4MP','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1184,'part',true),
    ('CAMERA-AHD-DOME-5MP','C?mera AHD dome 5MP','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1185,'part',true),
    ('CAMERA-AHD-DOME-8MP','C?mera AHD dome 8MP','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1186,'part',true),
    ('CAMERA-TVI-BULLET-720P','C?mera TVI bullet 720P','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1187,'part',true),
    ('CAMERA-TVI-BULLET-1080P','C?mera TVI bullet 1080P','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1188,'part',true),
    ('CAMERA-TVI-BULLET-4MP','C?mera TVI bullet 4MP','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1189,'part',true),
    ('CAMERA-TVI-BULLET-5MP','C?mera TVI bullet 5MP','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1190,'part',true),
    ('CAMERA-TVI-BULLET-8MP','C?mera TVI bullet 8MP','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1191,'part',true),
    ('CAMERA-TVI-DOME-720P','C?mera TVI dome 720P','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1192,'part',true),
    ('CAMERA-TVI-DOME-1080P','C?mera TVI dome 1080P','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1193,'part',true),
    ('CAMERA-TVI-DOME-4MP','C?mera TVI dome 4MP','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1194,'part',true),
    ('CAMERA-TVI-DOME-5MP','C?mera TVI dome 5MP','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1195,'part',true),
    ('CAMERA-TVI-DOME-8MP','C?mera TVI dome 8MP','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1196,'part',true),
    ('CAMERA-CVI-BULLET-720P','C?mera CVI bullet 720P','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1197,'part',true),
    ('CAMERA-CVI-BULLET-1080P','C?mera CVI bullet 1080P','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1198,'part',true),
    ('CAMERA-CVI-BULLET-4MP','C?mera CVI bullet 4MP','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1199,'part',true),
    ('CAMERA-CVI-BULLET-5MP','C?mera CVI bullet 5MP','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1200,'part',true),
    ('CAMERA-CVI-BULLET-8MP','C?mera CVI bullet 8MP','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1201,'part',true),
    ('CAMERA-CVI-DOME-720P','C?mera CVI dome 720P','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1202,'part',true),
    ('CAMERA-CVI-DOME-1080P','C?mera CVI dome 1080P','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1203,'part',true),
    ('CAMERA-CVI-DOME-4MP','C?mera CVI dome 4MP','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1204,'part',true),
    ('CAMERA-CVI-DOME-5MP','C?mera CVI dome 5MP','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1205,'part',true),
    ('CAMERA-CVI-DOME-8MP','C?mera CVI dome 8MP','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1206,'part',true),
    ('CAMERA-IP-BULLET-720P','C?mera IP bullet 720P','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1207,'part',true),
    ('CAMERA-IP-BULLET-1080P','C?mera IP bullet 1080P','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1208,'part',true),
    ('CAMERA-IP-BULLET-4MP','C?mera IP bullet 4MP','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1209,'part',true),
    ('CAMERA-IP-BULLET-5MP','C?mera IP bullet 5MP','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1210,'part',true),
    ('CAMERA-IP-BULLET-8MP','C?mera IP bullet 8MP','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1211,'part',true),
    ('CAMERA-IP-DOME-720P','C?mera IP dome 720P','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1212,'part',true),
    ('CAMERA-IP-DOME-1080P','C?mera IP dome 1080P','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1213,'part',true),
    ('CAMERA-IP-DOME-4MP','C?mera IP dome 4MP','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1214,'part',true),
    ('CAMERA-IP-DOME-5MP','C?mera IP dome 5MP','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1215,'part',true),
    ('CAMERA-IP-DOME-8MP','C?mera IP dome 8MP','C?mera sem marca definida.','un',0,0,'cftv_nvr_dvr',1216,'part',true),
    ('DVR-4CANAIS','DVR 4 canais','Gravador sem marca definida.','un',0,0,'cftv_nvr_dvr',1217,'part',true),
    ('NVR-4CANAIS','NVR 4 canais','Gravador IP sem marca definida.','un',0,0,'cftv_nvr_dvr',1218,'part',true),
    ('DVR-8CANAIS','DVR 8 canais','Gravador sem marca definida.','un',0,0,'cftv_nvr_dvr',1219,'part',true),
    ('NVR-8CANAIS','NVR 8 canais','Gravador IP sem marca definida.','un',0,0,'cftv_nvr_dvr',1220,'part',true),
    ('DVR-16CANAIS','DVR 16 canais','Gravador sem marca definida.','un',0,0,'cftv_nvr_dvr',1221,'part',true),
    ('NVR-16CANAIS','NVR 16 canais','Gravador IP sem marca definida.','un',0,0,'cftv_nvr_dvr',1222,'part',true),
    ('DVR-32CANAIS','DVR 32 canais','Gravador sem marca definida.','un',0,0,'cftv_nvr_dvr',1223,'part',true),
    ('NVR-32CANAIS','NVR 32 canais','Gravador IP sem marca definida.','un',0,0,'cftv_nvr_dvr',1224,'part',true),
    ('CABO-COAXIAL-M','Cabo coaxial por metro','Item CFTV sem marca definida.','m',0,0,'cftv_nvr_dvr',1225,'consumable',true),
    ('CABO-CFTV-BIPOLAR-M','Cabo CFTV bipolar por metro','Item CFTV sem marca definida.','m',0,0,'cftv_nvr_dvr',1226,'consumable',true),
    ('CONECTOR-BNC','Conector BNC','Item CFTV sem marca definida.','un',0,0,'cftv_nvr_dvr',1227,'consumable',true),
    ('P4-MACHO','Conector P4 macho','Item CFTV sem marca definida.','un',0,0,'cftv_nvr_dvr',1228,'consumable',true),
    ('P4-FEMEA','Conector P4 f?mea','Item CFTV sem marca definida.','un',0,0,'cftv_nvr_dvr',1229,'consumable',true),
    ('BALUN-PASSIVO','Balun passivo','Item CFTV sem marca definida.','un',0,0,'cftv_nvr_dvr',1230,'part',true),
    ('FONTE-12V-1A','Fonte 12 V 1 A','Item CFTV sem marca definida.','un',0,0,'cftv_nvr_dvr',1231,'part',true),
    ('FONTE-12V-2A','Fonte 12 V 2 A','Item CFTV sem marca definida.','un',0,0,'cftv_nvr_dvr',1232,'part',true),
    ('FONTE-12V-5A','Fonte 12 V 5 A','Item CFTV sem marca definida.','un',0,0,'cftv_nvr_dvr',1233,'part',true),
    ('FONTE-COLMEIA-12V-10A','Fonte colmeia 12 V 10 A','Item CFTV sem marca definida.','un',0,0,'cftv_nvr_dvr',1234,'part',true),
    ('CAIXA-PROTECAO-CAMERA','Caixa de prote??o para c?mera','Item CFTV sem marca definida.','un',0,0,'cftv_nvr_dvr',1235,'part',true),
    ('CABO-HDMI-1M','Cabo HDMI 1 m','Item sem marca definida.','un',0,0,'troca_componente',1236,'part',true),
    ('CABO-HDMI-2M','Cabo HDMI 2 m','Item sem marca definida.','un',0,0,'troca_componente',1237,'part',true),
    ('CABO-HDMI-5M','Cabo HDMI 5 m','Item sem marca definida.','un',0,0,'troca_componente',1238,'part',true),
    ('CABO-VGA','Cabo VGA','Item sem marca definida.','un',0,0,'troca_componente',1239,'part',true),
    ('CABO-DISPLAYPORT','Cabo DisplayPort','Item sem marca definida.','un',0,0,'troca_componente',1240,'part',true),
    ('CABO-DVI','Cabo DVI','Item sem marca definida.','un',0,0,'troca_componente',1241,'part',true),
    ('CABO-USB-A-B','Cabo USB A-B impressora','Item sem marca definida.','un',0,0,'impressao_perifericos',1242,'part',true),
    ('CABO-USB-C','Cabo USB-C','Item sem marca definida.','un',0,0,'troca_componente',1243,'part',true),
    ('CABO-FORCA-PC','Cabo de for?a PC','Item sem marca definida.','un',0,0,'energia_nobreak',1244,'part',true),
    ('ADAPTADOR-HDMI-VGA','Adaptador HDMI para VGA','Item sem marca definida.','un',0,0,'troca_componente',1245,'part',true),
    ('ADAPTADOR-DP-HDMI','Adaptador DisplayPort para HDMI','Item sem marca definida.','un',0,0,'troca_componente',1246,'part',true),
    ('TECLADO-USB','Teclado USB','Item sem marca definida.','un',0,0,'impressao_perifericos',1247,'part',true),
    ('TECLADO-WIRELESS','Teclado sem fio','Item sem marca definida.','un',0,0,'impressao_perifericos',1248,'part',true),
    ('MOUSE-USB','Mouse USB','Item sem marca definida.','un',0,0,'impressao_perifericos',1249,'part',true),
    ('MOUSE-WIRELESS','Mouse sem fio','Item sem marca definida.','un',0,0,'impressao_perifericos',1250,'part',true),
    ('WEBCAM-USB','Webcam USB','Item sem marca definida.','un',0,0,'impressao_perifericos',1251,'part',true),
    ('HEADSET-USB','Headset USB','Item sem marca definida.','un',0,0,'impressao_perifericos',1252,'part',true),
    ('LEITOR-CERTIFICADO-USB','Leitor certificado digital USB','Item sem marca definida.','un',0,0,'impressao_perifericos',1253,'part',true),
    ('FILTRO-LINHA','Filtro de linha','Item sem marca definida.','un',0,0,'energia_nobreak',1254,'part',true),
    ('NOBREAK-BATERIA-12V-7AH','Bateria nobreak 12 V 7 Ah','Item sem marca definida.','un',0,0,'energia_nobreak',1255,'part',true),
    ('NOBREAK-BATERIA-12V-9AH','Bateria nobreak 12 V 9 Ah','Item sem marca definida.','un',0,0,'energia_nobreak',1256,'part',true),
    ('PASTA-TERMICA-G','Pasta t?rmica por grama','Consum?vel t?cnico sem marca definida.','g',0,0,'manutencao_hardware',1257,'consumable',true),
    ('ALCOOL-ISOPROPILICO-ML','?lcool isoprop?lico por ml','Consum?vel t?cnico sem marca definida.','ml',0,0,'manutencao_hardware',1258,'consumable',true),
    ('LIMPA-CONTATO-ML','Limpa contato por ml','Consum?vel t?cnico sem marca definida.','ml',0,0,'manutencao_hardware',1259,'consumable',true),
    ('AR-COMPRIMIDO-ML','Ar comprimido por ml','Consum?vel t?cnico sem marca definida.','ml',0,0,'manutencao_hardware',1260,'consumable',true),
    ('PANO-MICROFIBRA','Pano de microfibra','Consum?vel t?cnico sem marca definida.','un',0,0,'manutencao_hardware',1261,'consumable',true),
    ('PARAFUSO-GABINETE','Parafuso de gabinete','Consum?vel t?cnico sem marca definida.','un',0,0,'manutencao_hardware',1262,'consumable',true),
    ('PARAFUSO-SSD-M2','Parafuso SSD M.2','Consum?vel t?cnico sem marca definida.','un',0,0,'manutencao_hardware',1263,'consumable',true),
    ('VELCRO-CABO-M','Velcro organizador por metro','Consum?vel t?cnico sem marca definida.','m',0,0,'manutencao_hardware',1264,'consumable',true)
ON CONFLICT (sku) DO UPDATE SET
    label=excluded.label,
    description=excluded.description,
    unit=excluded.unit,
    ticket_type_key=excluded.ticket_type_key,
    position=excluded.position,
    item_kind=excluded.item_kind,
    requires_invoice_photo=excluded.requires_invoice_photo,
    active=true,
    updated_at=now();
