-- TGDesk: taxonomia planejada de tipos de chamado e campos din?micos.
-- O cliente recebe textos/campos; o servidor mant?m os tipos e v?nculos com servi?os.

INSERT INTO ticket_types(key,label,icon,position) VALUES
    ('diagnostico_geral','Diagn?stico geral','troubleshoot_outlined',100),
    ('lentidao_intermitente','Lentid?o intermitente','speed_outlined',110),
    ('manutencao_sistema_operacional','Sistema operacional','terminal_outlined',120),
    ('malware_seguranca','Malware e seguran?a','security_outlined',130),
    ('driver_firmware_bios','Driver, firmware e BIOS','developer_board_outlined',140),
    ('backup_migracao_dados','Backup, migra??o e dados','backup_outlined',150),
    ('instalacao_programas','Instala??o de programas','apps_outlined',160),
    ('certificado_erp_email','Certificado, ERP e e-mail','badge_outlined',170),
    ('hardware_desktop','Hardware desktop','desktop_windows_outlined',200),
    ('hardware_notebook','Hardware notebook','laptop_windows_outlined',210),
    ('troca_memoria','Troca/expans?o de mem?ria','memory_outlined',220),
    ('troca_armazenamento','Troca de HD/SSD','storage_outlined',230),
    ('troca_fonte_energia_pc','Fonte/energia do computador','power_outlined',240),
    ('troca_placa_processador','Placa-m?e, processador e GPU','developer_board_outlined',250),
    ('limpeza_termica','Limpeza t?rmica/preventiva','cleaning_services_outlined',260),
    ('perifericos_usb_audio_video','Perif?ricos USB, ?udio e v?deo','usb_outlined',300),
    ('impressora_scanner','Impressora e scanner','print_outlined',310),
    ('rede_diagnostico','Diagn?stico de rede','lan_outlined',400),
    ('rede_cabeamento','Cabeamento estruturado','settings_ethernet_outlined',410),
    ('rede_wifi','Wi-Fi e mesh','wifi_outlined',420),
    ('rede_roteador_firewall','Roteador, firewall e VLAN','router_outlined',430),
    ('rede_rack_switch','Rack, switch e patch panel','dns_outlined',440),
    ('cftv_camera','C?meras CFTV','videocam_outlined',500),
    ('cftv_gravador','DVR/NVR/grava??o','video_settings_outlined',510),
    ('cftv_acesso_remoto','Acesso remoto CFTV','phone_iphone_outlined',520),
    ('energia_nobreak_bateria','Nobreak e bateria','battery_charging_full_outlined',600),
    ('energia_tomada_protecao','Tomada, filtro e prote??o','electrical_services_outlined',610),
    ('atendimento_avulso_orientacao','Orienta??o t?cnica avulsa','support_agent_outlined',700),
    ('instalacao_postos_loja','Instala??o de posto/loja','store_outlined',710),
    ('manutencao_preventiva_contrato','Manuten??o preventiva de contrato','event_available_outlined',720)
ON CONFLICT (key) DO UPDATE SET
    label=excluded.label,
    icon=excluded.icon,
    position=excluded.position,
    active=true,
    updated_at=now();

INSERT INTO ticket_type_fields
    (type_key,field_key,label,help,kind,options,required,depends_on,depends_value,position) VALUES
    ('diagnostico_geral','description','O que est? acontecendo','Descreva o sintoma principal com as suas palavras.','multiline','[]'::jsonb,true,NULL,NULL,10),
    ('diagnostico_geral','urgency','Urg?ncia','Impacto operacional do problema.','choice','[{"value":"low","label":"Baixa"},{"value":"normal","label":"Normal"},{"value":"high","label":"Alta"},{"value":"critical","label":"Cr?tica"}]'::jsonb,false,NULL,NULL,20),
    ('diagnostico_geral','asset_type','Equipamento afetado','Tipo de equipamento ou ambiente relacionado ao chamado.','choice','[{"value":"pc","label":"PC"},{"value":"notebook","label":"Notebook"},{"value":"rede","label":"Rede"},{"value":"cftv","label":"CFTV"},{"value":"impressora","label":"Impressora"},{"value":"energia","label":"Energia"},{"value":"outro","label":"Outro"}]'::jsonb,false,NULL,NULL,30),
    ('diagnostico_geral','modality_note','Observa??o de modalidade','Informe se h? restri??o para remoto, presencial, hor?rio ou acesso.','text','[]'::jsonb,false,NULL,NULL,40),
    ('diagnostico_geral','address','Endere?o do atendimento','Obrigat?rio quando o atendimento for presencial.','text','[]'::jsonb,true,'modality','onsite',50),
    ('diagnostico_geral','attachments','Fotos/evid?ncias iniciais','Fotos, prints, nota fiscal ou v?deos curtos que ajudem o diagn?stico.','attachment','[]'::jsonb,false,NULL,NULL,90),
    ('lentidao_intermitente','description','O que est? acontecendo','Descreva o sintoma principal com as suas palavras.','multiline','[]'::jsonb,true,NULL,NULL,10),
    ('lentidao_intermitente','urgency','Urg?ncia','Impacto operacional do problema.','choice','[{"value":"low","label":"Baixa"},{"value":"normal","label":"Normal"},{"value":"high","label":"Alta"},{"value":"critical","label":"Cr?tica"}]'::jsonb,false,NULL,NULL,20),
    ('lentidao_intermitente','asset_type','Equipamento afetado','Tipo de equipamento ou ambiente relacionado ao chamado.','choice','[{"value":"pc","label":"PC"},{"value":"notebook","label":"Notebook"},{"value":"rede","label":"Rede"},{"value":"cftv","label":"CFTV"},{"value":"impressora","label":"Impressora"},{"value":"energia","label":"Energia"},{"value":"outro","label":"Outro"}]'::jsonb,false,NULL,NULL,30),
    ('lentidao_intermitente','modality_note','Observa??o de modalidade','Informe se h? restri??o para remoto, presencial, hor?rio ou acesso.','text','[]'::jsonb,false,NULL,NULL,40),
    ('lentidao_intermitente','address','Endere?o do atendimento','Obrigat?rio quando o atendimento for presencial.','text','[]'::jsonb,true,'modality','onsite',50),
    ('lentidao_intermitente','attachments','Fotos/evid?ncias iniciais','Fotos, prints, nota fiscal ou v?deos curtos que ajudem o diagn?stico.','attachment','[]'::jsonb,false,NULL,NULL,90),
    ('lentidao_intermitente','when_happens','Quando a lentid?o acontece','Ex.: ao abrir navegador, OBS, reuni?o, depois de horas ligado.','multiline','[]'::jsonb,true,NULL,NULL,60),
    ('lentidao_intermitente','after_reboot_improves','Melhora ap?s reiniciar?','Marque se reiniciar resolve temporariamente.','bool','[]'::jsonb,false,NULL,NULL,70),
    ('lentidao_intermitente','suspected_apps','Programas suspeitos','Ex.: OBS, c?mera virtual, antiv?rus, navegador, ERP.','text','[]'::jsonb,false,NULL,NULL,80),
    ('manutencao_sistema_operacional','description','O que est? acontecendo','Descreva o sintoma principal com as suas palavras.','multiline','[]'::jsonb,true,NULL,NULL,10),
    ('manutencao_sistema_operacional','urgency','Urg?ncia','Impacto operacional do problema.','choice','[{"value":"low","label":"Baixa"},{"value":"normal","label":"Normal"},{"value":"high","label":"Alta"},{"value":"critical","label":"Cr?tica"}]'::jsonb,false,NULL,NULL,20),
    ('manutencao_sistema_operacional','asset_type','Equipamento afetado','Tipo de equipamento ou ambiente relacionado ao chamado.','choice','[{"value":"pc","label":"PC"},{"value":"notebook","label":"Notebook"},{"value":"rede","label":"Rede"},{"value":"cftv","label":"CFTV"},{"value":"impressora","label":"Impressora"},{"value":"energia","label":"Energia"},{"value":"outro","label":"Outro"}]'::jsonb,false,NULL,NULL,30),
    ('manutencao_sistema_operacional','modality_note','Observa??o de modalidade','Informe se h? restri??o para remoto, presencial, hor?rio ou acesso.','text','[]'::jsonb,false,NULL,NULL,40),
    ('manutencao_sistema_operacional','address','Endere?o do atendimento','Obrigat?rio quando o atendimento for presencial.','text','[]'::jsonb,true,'modality','onsite',50),
    ('manutencao_sistema_operacional','attachments','Fotos/evid?ncias iniciais','Fotos, prints, nota fiscal ou v?deos curtos que ajudem o diagn?stico.','attachment','[]'::jsonb,false,NULL,NULL,90),
    ('malware_seguranca','description','O que est? acontecendo','Descreva o sintoma principal com as suas palavras.','multiline','[]'::jsonb,true,NULL,NULL,10),
    ('malware_seguranca','urgency','Urg?ncia','Impacto operacional do problema.','choice','[{"value":"low","label":"Baixa"},{"value":"normal","label":"Normal"},{"value":"high","label":"Alta"},{"value":"critical","label":"Cr?tica"}]'::jsonb,false,NULL,NULL,20),
    ('malware_seguranca','asset_type','Equipamento afetado','Tipo de equipamento ou ambiente relacionado ao chamado.','choice','[{"value":"pc","label":"PC"},{"value":"notebook","label":"Notebook"},{"value":"rede","label":"Rede"},{"value":"cftv","label":"CFTV"},{"value":"impressora","label":"Impressora"},{"value":"energia","label":"Energia"},{"value":"outro","label":"Outro"}]'::jsonb,false,NULL,NULL,30),
    ('malware_seguranca','modality_note','Observa??o de modalidade','Informe se h? restri??o para remoto, presencial, hor?rio ou acesso.','text','[]'::jsonb,false,NULL,NULL,40),
    ('malware_seguranca','address','Endere?o do atendimento','Obrigat?rio quando o atendimento for presencial.','text','[]'::jsonb,true,'modality','onsite',50),
    ('malware_seguranca','attachments','Fotos/evid?ncias iniciais','Fotos, prints, nota fiscal ou v?deos curtos que ajudem o diagn?stico.','attachment','[]'::jsonb,false,NULL,NULL,90),
    ('driver_firmware_bios','description','O que est? acontecendo','Descreva o sintoma principal com as suas palavras.','multiline','[]'::jsonb,true,NULL,NULL,10),
    ('driver_firmware_bios','urgency','Urg?ncia','Impacto operacional do problema.','choice','[{"value":"low","label":"Baixa"},{"value":"normal","label":"Normal"},{"value":"high","label":"Alta"},{"value":"critical","label":"Cr?tica"}]'::jsonb,false,NULL,NULL,20),
    ('driver_firmware_bios','asset_type','Equipamento afetado','Tipo de equipamento ou ambiente relacionado ao chamado.','choice','[{"value":"pc","label":"PC"},{"value":"notebook","label":"Notebook"},{"value":"rede","label":"Rede"},{"value":"cftv","label":"CFTV"},{"value":"impressora","label":"Impressora"},{"value":"energia","label":"Energia"},{"value":"outro","label":"Outro"}]'::jsonb,false,NULL,NULL,30),
    ('driver_firmware_bios','modality_note','Observa??o de modalidade','Informe se h? restri??o para remoto, presencial, hor?rio ou acesso.','text','[]'::jsonb,false,NULL,NULL,40),
    ('driver_firmware_bios','address','Endere?o do atendimento','Obrigat?rio quando o atendimento for presencial.','text','[]'::jsonb,true,'modality','onsite',50),
    ('driver_firmware_bios','attachments','Fotos/evid?ncias iniciais','Fotos, prints, nota fiscal ou v?deos curtos que ajudem o diagn?stico.','attachment','[]'::jsonb,false,NULL,NULL,90),
    ('backup_migracao_dados','description','O que est? acontecendo','Descreva o sintoma principal com as suas palavras.','multiline','[]'::jsonb,true,NULL,NULL,10),
    ('backup_migracao_dados','urgency','Urg?ncia','Impacto operacional do problema.','choice','[{"value":"low","label":"Baixa"},{"value":"normal","label":"Normal"},{"value":"high","label":"Alta"},{"value":"critical","label":"Cr?tica"}]'::jsonb,false,NULL,NULL,20),
    ('backup_migracao_dados','asset_type','Equipamento afetado','Tipo de equipamento ou ambiente relacionado ao chamado.','choice','[{"value":"pc","label":"PC"},{"value":"notebook","label":"Notebook"},{"value":"rede","label":"Rede"},{"value":"cftv","label":"CFTV"},{"value":"impressora","label":"Impressora"},{"value":"energia","label":"Energia"},{"value":"outro","label":"Outro"}]'::jsonb,false,NULL,NULL,30),
    ('backup_migracao_dados','modality_note','Observa??o de modalidade','Informe se h? restri??o para remoto, presencial, hor?rio ou acesso.','text','[]'::jsonb,false,NULL,NULL,40),
    ('backup_migracao_dados','address','Endere?o do atendimento','Obrigat?rio quando o atendimento for presencial.','text','[]'::jsonb,true,'modality','onsite',50),
    ('backup_migracao_dados','attachments','Fotos/evid?ncias iniciais','Fotos, prints, nota fiscal ou v?deos curtos que ajudem o diagn?stico.','attachment','[]'::jsonb,false,NULL,NULL,90),
    ('instalacao_programas','description','O que est? acontecendo','Descreva o sintoma principal com as suas palavras.','multiline','[]'::jsonb,true,NULL,NULL,10),
    ('instalacao_programas','urgency','Urg?ncia','Impacto operacional do problema.','choice','[{"value":"low","label":"Baixa"},{"value":"normal","label":"Normal"},{"value":"high","label":"Alta"},{"value":"critical","label":"Cr?tica"}]'::jsonb,false,NULL,NULL,20),
    ('instalacao_programas','asset_type','Equipamento afetado','Tipo de equipamento ou ambiente relacionado ao chamado.','choice','[{"value":"pc","label":"PC"},{"value":"notebook","label":"Notebook"},{"value":"rede","label":"Rede"},{"value":"cftv","label":"CFTV"},{"value":"impressora","label":"Impressora"},{"value":"energia","label":"Energia"},{"value":"outro","label":"Outro"}]'::jsonb,false,NULL,NULL,30),
    ('instalacao_programas','modality_note','Observa??o de modalidade','Informe se h? restri??o para remoto, presencial, hor?rio ou acesso.','text','[]'::jsonb,false,NULL,NULL,40),
    ('instalacao_programas','address','Endere?o do atendimento','Obrigat?rio quando o atendimento for presencial.','text','[]'::jsonb,true,'modality','onsite',50),
    ('instalacao_programas','attachments','Fotos/evid?ncias iniciais','Fotos, prints, nota fiscal ou v?deos curtos que ajudem o diagn?stico.','attachment','[]'::jsonb,false,NULL,NULL,90),
    ('certificado_erp_email','description','O que est? acontecendo','Descreva o sintoma principal com as suas palavras.','multiline','[]'::jsonb,true,NULL,NULL,10),
    ('certificado_erp_email','urgency','Urg?ncia','Impacto operacional do problema.','choice','[{"value":"low","label":"Baixa"},{"value":"normal","label":"Normal"},{"value":"high","label":"Alta"},{"value":"critical","label":"Cr?tica"}]'::jsonb,false,NULL,NULL,20),
    ('certificado_erp_email','asset_type','Equipamento afetado','Tipo de equipamento ou ambiente relacionado ao chamado.','choice','[{"value":"pc","label":"PC"},{"value":"notebook","label":"Notebook"},{"value":"rede","label":"Rede"},{"value":"cftv","label":"CFTV"},{"value":"impressora","label":"Impressora"},{"value":"energia","label":"Energia"},{"value":"outro","label":"Outro"}]'::jsonb,false,NULL,NULL,30),
    ('certificado_erp_email','modality_note','Observa??o de modalidade','Informe se h? restri??o para remoto, presencial, hor?rio ou acesso.','text','[]'::jsonb,false,NULL,NULL,40),
    ('certificado_erp_email','address','Endere?o do atendimento','Obrigat?rio quando o atendimento for presencial.','text','[]'::jsonb,true,'modality','onsite',50),
    ('certificado_erp_email','attachments','Fotos/evid?ncias iniciais','Fotos, prints, nota fiscal ou v?deos curtos que ajudem o diagn?stico.','attachment','[]'::jsonb,false,NULL,NULL,90),
    ('hardware_desktop','description','O que est? acontecendo','Descreva o sintoma principal com as suas palavras.','multiline','[]'::jsonb,true,NULL,NULL,10),
    ('hardware_desktop','urgency','Urg?ncia','Impacto operacional do problema.','choice','[{"value":"low","label":"Baixa"},{"value":"normal","label":"Normal"},{"value":"high","label":"Alta"},{"value":"critical","label":"Cr?tica"}]'::jsonb,false,NULL,NULL,20),
    ('hardware_desktop','asset_type','Equipamento afetado','Tipo de equipamento ou ambiente relacionado ao chamado.','choice','[{"value":"pc","label":"PC"},{"value":"notebook","label":"Notebook"},{"value":"rede","label":"Rede"},{"value":"cftv","label":"CFTV"},{"value":"impressora","label":"Impressora"},{"value":"energia","label":"Energia"},{"value":"outro","label":"Outro"}]'::jsonb,false,NULL,NULL,30),
    ('hardware_desktop','modality_note','Observa??o de modalidade','Informe se h? restri??o para remoto, presencial, hor?rio ou acesso.','text','[]'::jsonb,false,NULL,NULL,40),
    ('hardware_desktop','address','Endere?o do atendimento','Obrigat?rio quando o atendimento for presencial.','text','[]'::jsonb,true,'modality','onsite',50),
    ('hardware_desktop','attachments','Fotos/evid?ncias iniciais','Fotos, prints, nota fiscal ou v?deos curtos que ajudem o diagn?stico.','attachment','[]'::jsonb,false,NULL,NULL,90),
    ('hardware_notebook','description','O que est? acontecendo','Descreva o sintoma principal com as suas palavras.','multiline','[]'::jsonb,true,NULL,NULL,10),
    ('hardware_notebook','urgency','Urg?ncia','Impacto operacional do problema.','choice','[{"value":"low","label":"Baixa"},{"value":"normal","label":"Normal"},{"value":"high","label":"Alta"},{"value":"critical","label":"Cr?tica"}]'::jsonb,false,NULL,NULL,20),
    ('hardware_notebook','asset_type','Equipamento afetado','Tipo de equipamento ou ambiente relacionado ao chamado.','choice','[{"value":"pc","label":"PC"},{"value":"notebook","label":"Notebook"},{"value":"rede","label":"Rede"},{"value":"cftv","label":"CFTV"},{"value":"impressora","label":"Impressora"},{"value":"energia","label":"Energia"},{"value":"outro","label":"Outro"}]'::jsonb,false,NULL,NULL,30),
    ('hardware_notebook','modality_note','Observa??o de modalidade','Informe se h? restri??o para remoto, presencial, hor?rio ou acesso.','text','[]'::jsonb,false,NULL,NULL,40),
    ('hardware_notebook','address','Endere?o do atendimento','Obrigat?rio quando o atendimento for presencial.','text','[]'::jsonb,true,'modality','onsite',50),
    ('hardware_notebook','attachments','Fotos/evid?ncias iniciais','Fotos, prints, nota fiscal ou v?deos curtos que ajudem o diagn?stico.','attachment','[]'::jsonb,false,NULL,NULL,90),
    ('hardware_notebook','notebook_symptom','Sintoma do notebook','Tela, teclado, bateria, carregador, aquecimento ou queda.','choice','[{"value":"screen","label":"Tela"},{"value":"keyboard","label":"Teclado"},{"value":"battery","label":"Bateria"},{"value":"charger","label":"Carregador"},{"value":"thermal","label":"Aquecimento"},{"value":"other","label":"Outro"}]'::jsonb,true,NULL,NULL,60),
    ('troca_memoria','description','O que est? acontecendo','Descreva o sintoma principal com as suas palavras.','multiline','[]'::jsonb,true,NULL,NULL,10),
    ('troca_memoria','urgency','Urg?ncia','Impacto operacional do problema.','choice','[{"value":"low","label":"Baixa"},{"value":"normal","label":"Normal"},{"value":"high","label":"Alta"},{"value":"critical","label":"Cr?tica"}]'::jsonb,false,NULL,NULL,20),
    ('troca_memoria','asset_type','Equipamento afetado','Tipo de equipamento ou ambiente relacionado ao chamado.','choice','[{"value":"pc","label":"PC"},{"value":"notebook","label":"Notebook"},{"value":"rede","label":"Rede"},{"value":"cftv","label":"CFTV"},{"value":"impressora","label":"Impressora"},{"value":"energia","label":"Energia"},{"value":"outro","label":"Outro"}]'::jsonb,false,NULL,NULL,30),
    ('troca_memoria','modality_note','Observa??o de modalidade','Informe se h? restri??o para remoto, presencial, hor?rio ou acesso.','text','[]'::jsonb,false,NULL,NULL,40),
    ('troca_memoria','address','Endere?o do atendimento','Obrigat?rio quando o atendimento for presencial.','text','[]'::jsonb,true,'modality','onsite',50),
    ('troca_memoria','attachments','Fotos/evid?ncias iniciais','Fotos, prints, nota fiscal ou v?deos curtos que ajudem o diagn?stico.','attachment','[]'::jsonb,false,NULL,NULL,90),
    ('troca_armazenamento','description','O que est? acontecendo','Descreva o sintoma principal com as suas palavras.','multiline','[]'::jsonb,true,NULL,NULL,10),
    ('troca_armazenamento','urgency','Urg?ncia','Impacto operacional do problema.','choice','[{"value":"low","label":"Baixa"},{"value":"normal","label":"Normal"},{"value":"high","label":"Alta"},{"value":"critical","label":"Cr?tica"}]'::jsonb,false,NULL,NULL,20),
    ('troca_armazenamento','asset_type','Equipamento afetado','Tipo de equipamento ou ambiente relacionado ao chamado.','choice','[{"value":"pc","label":"PC"},{"value":"notebook","label":"Notebook"},{"value":"rede","label":"Rede"},{"value":"cftv","label":"CFTV"},{"value":"impressora","label":"Impressora"},{"value":"energia","label":"Energia"},{"value":"outro","label":"Outro"}]'::jsonb,false,NULL,NULL,30),
    ('troca_armazenamento','modality_note','Observa??o de modalidade','Informe se h? restri??o para remoto, presencial, hor?rio ou acesso.','text','[]'::jsonb,false,NULL,NULL,40),
    ('troca_armazenamento','address','Endere?o do atendimento','Obrigat?rio quando o atendimento for presencial.','text','[]'::jsonb,true,'modality','onsite',50),
    ('troca_armazenamento','attachments','Fotos/evid?ncias iniciais','Fotos, prints, nota fiscal ou v?deos curtos que ajudem o diagn?stico.','attachment','[]'::jsonb,false,NULL,NULL,90),
    ('troca_fonte_energia_pc','description','O que est? acontecendo','Descreva o sintoma principal com as suas palavras.','multiline','[]'::jsonb,true,NULL,NULL,10),
    ('troca_fonte_energia_pc','urgency','Urg?ncia','Impacto operacional do problema.','choice','[{"value":"low","label":"Baixa"},{"value":"normal","label":"Normal"},{"value":"high","label":"Alta"},{"value":"critical","label":"Cr?tica"}]'::jsonb,false,NULL,NULL,20),
    ('troca_fonte_energia_pc','asset_type','Equipamento afetado','Tipo de equipamento ou ambiente relacionado ao chamado.','choice','[{"value":"pc","label":"PC"},{"value":"notebook","label":"Notebook"},{"value":"rede","label":"Rede"},{"value":"cftv","label":"CFTV"},{"value":"impressora","label":"Impressora"},{"value":"energia","label":"Energia"},{"value":"outro","label":"Outro"}]'::jsonb,false,NULL,NULL,30),
    ('troca_fonte_energia_pc','modality_note','Observa??o de modalidade','Informe se h? restri??o para remoto, presencial, hor?rio ou acesso.','text','[]'::jsonb,false,NULL,NULL,40),
    ('troca_fonte_energia_pc','address','Endere?o do atendimento','Obrigat?rio quando o atendimento for presencial.','text','[]'::jsonb,true,'modality','onsite',50),
    ('troca_fonte_energia_pc','attachments','Fotos/evid?ncias iniciais','Fotos, prints, nota fiscal ou v?deos curtos que ajudem o diagn?stico.','attachment','[]'::jsonb,false,NULL,NULL,90),
    ('troca_placa_processador','description','O que est? acontecendo','Descreva o sintoma principal com as suas palavras.','multiline','[]'::jsonb,true,NULL,NULL,10),
    ('troca_placa_processador','urgency','Urg?ncia','Impacto operacional do problema.','choice','[{"value":"low","label":"Baixa"},{"value":"normal","label":"Normal"},{"value":"high","label":"Alta"},{"value":"critical","label":"Cr?tica"}]'::jsonb,false,NULL,NULL,20),
    ('troca_placa_processador','asset_type','Equipamento afetado','Tipo de equipamento ou ambiente relacionado ao chamado.','choice','[{"value":"pc","label":"PC"},{"value":"notebook","label":"Notebook"},{"value":"rede","label":"Rede"},{"value":"cftv","label":"CFTV"},{"value":"impressora","label":"Impressora"},{"value":"energia","label":"Energia"},{"value":"outro","label":"Outro"}]'::jsonb,false,NULL,NULL,30),
    ('troca_placa_processador','modality_note','Observa??o de modalidade','Informe se h? restri??o para remoto, presencial, hor?rio ou acesso.','text','[]'::jsonb,false,NULL,NULL,40),
    ('troca_placa_processador','address','Endere?o do atendimento','Obrigat?rio quando o atendimento for presencial.','text','[]'::jsonb,true,'modality','onsite',50),
    ('troca_placa_processador','attachments','Fotos/evid?ncias iniciais','Fotos, prints, nota fiscal ou v?deos curtos que ajudem o diagn?stico.','attachment','[]'::jsonb,false,NULL,NULL,90),
    ('limpeza_termica','description','O que est? acontecendo','Descreva o sintoma principal com as suas palavras.','multiline','[]'::jsonb,true,NULL,NULL,10),
    ('limpeza_termica','urgency','Urg?ncia','Impacto operacional do problema.','choice','[{"value":"low","label":"Baixa"},{"value":"normal","label":"Normal"},{"value":"high","label":"Alta"},{"value":"critical","label":"Cr?tica"}]'::jsonb,false,NULL,NULL,20),
    ('limpeza_termica','asset_type','Equipamento afetado','Tipo de equipamento ou ambiente relacionado ao chamado.','choice','[{"value":"pc","label":"PC"},{"value":"notebook","label":"Notebook"},{"value":"rede","label":"Rede"},{"value":"cftv","label":"CFTV"},{"value":"impressora","label":"Impressora"},{"value":"energia","label":"Energia"},{"value":"outro","label":"Outro"}]'::jsonb,false,NULL,NULL,30),
    ('limpeza_termica','modality_note','Observa??o de modalidade','Informe se h? restri??o para remoto, presencial, hor?rio ou acesso.','text','[]'::jsonb,false,NULL,NULL,40),
    ('limpeza_termica','address','Endere?o do atendimento','Obrigat?rio quando o atendimento for presencial.','text','[]'::jsonb,true,'modality','onsite',50),
    ('limpeza_termica','attachments','Fotos/evid?ncias iniciais','Fotos, prints, nota fiscal ou v?deos curtos que ajudem o diagn?stico.','attachment','[]'::jsonb,false,NULL,NULL,90),
    ('perifericos_usb_audio_video','description','O que est? acontecendo','Descreva o sintoma principal com as suas palavras.','multiline','[]'::jsonb,true,NULL,NULL,10),
    ('perifericos_usb_audio_video','urgency','Urg?ncia','Impacto operacional do problema.','choice','[{"value":"low","label":"Baixa"},{"value":"normal","label":"Normal"},{"value":"high","label":"Alta"},{"value":"critical","label":"Cr?tica"}]'::jsonb,false,NULL,NULL,20),
    ('perifericos_usb_audio_video','asset_type','Equipamento afetado','Tipo de equipamento ou ambiente relacionado ao chamado.','choice','[{"value":"pc","label":"PC"},{"value":"notebook","label":"Notebook"},{"value":"rede","label":"Rede"},{"value":"cftv","label":"CFTV"},{"value":"impressora","label":"Impressora"},{"value":"energia","label":"Energia"},{"value":"outro","label":"Outro"}]'::jsonb,false,NULL,NULL,30),
    ('perifericos_usb_audio_video','modality_note','Observa??o de modalidade','Informe se h? restri??o para remoto, presencial, hor?rio ou acesso.','text','[]'::jsonb,false,NULL,NULL,40),
    ('perifericos_usb_audio_video','address','Endere?o do atendimento','Obrigat?rio quando o atendimento for presencial.','text','[]'::jsonb,true,'modality','onsite',50),
    ('perifericos_usb_audio_video','attachments','Fotos/evid?ncias iniciais','Fotos, prints, nota fiscal ou v?deos curtos que ajudem o diagn?stico.','attachment','[]'::jsonb,false,NULL,NULL,90),
    ('impressora_scanner','description','O que est? acontecendo','Descreva o sintoma principal com as suas palavras.','multiline','[]'::jsonb,true,NULL,NULL,10),
    ('impressora_scanner','urgency','Urg?ncia','Impacto operacional do problema.','choice','[{"value":"low","label":"Baixa"},{"value":"normal","label":"Normal"},{"value":"high","label":"Alta"},{"value":"critical","label":"Cr?tica"}]'::jsonb,false,NULL,NULL,20),
    ('impressora_scanner','asset_type','Equipamento afetado','Tipo de equipamento ou ambiente relacionado ao chamado.','choice','[{"value":"pc","label":"PC"},{"value":"notebook","label":"Notebook"},{"value":"rede","label":"Rede"},{"value":"cftv","label":"CFTV"},{"value":"impressora","label":"Impressora"},{"value":"energia","label":"Energia"},{"value":"outro","label":"Outro"}]'::jsonb,false,NULL,NULL,30),
    ('impressora_scanner','modality_note','Observa??o de modalidade','Informe se h? restri??o para remoto, presencial, hor?rio ou acesso.','text','[]'::jsonb,false,NULL,NULL,40),
    ('impressora_scanner','address','Endere?o do atendimento','Obrigat?rio quando o atendimento for presencial.','text','[]'::jsonb,true,'modality','onsite',50),
    ('impressora_scanner','attachments','Fotos/evid?ncias iniciais','Fotos, prints, nota fiscal ou v?deos curtos que ajudem o diagn?stico.','attachment','[]'::jsonb,false,NULL,NULL,90),
    ('impressora_scanner','printer_connection','Conex?o da impressora','USB, rede cabeada, Wi-Fi ou compartilhada.','choice','[{"value":"usb","label":"USB"},{"value":"ethernet","label":"Rede cabeada"},{"value":"wifi","label":"Wi-Fi"},{"value":"shared","label":"Compartilhada"},{"value":"unknown","label":"N?o sei"}]'::jsonb,false,NULL,NULL,60),
    ('rede_diagnostico','description','O que est? acontecendo','Descreva o sintoma principal com as suas palavras.','multiline','[]'::jsonb,true,NULL,NULL,10),
    ('rede_diagnostico','urgency','Urg?ncia','Impacto operacional do problema.','choice','[{"value":"low","label":"Baixa"},{"value":"normal","label":"Normal"},{"value":"high","label":"Alta"},{"value":"critical","label":"Cr?tica"}]'::jsonb,false,NULL,NULL,20),
    ('rede_diagnostico','asset_type','Equipamento afetado','Tipo de equipamento ou ambiente relacionado ao chamado.','choice','[{"value":"pc","label":"PC"},{"value":"notebook","label":"Notebook"},{"value":"rede","label":"Rede"},{"value":"cftv","label":"CFTV"},{"value":"impressora","label":"Impressora"},{"value":"energia","label":"Energia"},{"value":"outro","label":"Outro"}]'::jsonb,false,NULL,NULL,30),
    ('rede_diagnostico','modality_note','Observa??o de modalidade','Informe se h? restri??o para remoto, presencial, hor?rio ou acesso.','text','[]'::jsonb,false,NULL,NULL,40),
    ('rede_diagnostico','address','Endere?o do atendimento','Obrigat?rio quando o atendimento for presencial.','text','[]'::jsonb,true,'modality','onsite',50),
    ('rede_diagnostico','attachments','Fotos/evid?ncias iniciais','Fotos, prints, nota fiscal ou v?deos curtos que ajudem o diagn?stico.','attachment','[]'::jsonb,false,NULL,NULL,90),
    ('rede_cabeamento','description','O que est? acontecendo','Descreva o sintoma principal com as suas palavras.','multiline','[]'::jsonb,true,NULL,NULL,10),
    ('rede_cabeamento','urgency','Urg?ncia','Impacto operacional do problema.','choice','[{"value":"low","label":"Baixa"},{"value":"normal","label":"Normal"},{"value":"high","label":"Alta"},{"value":"critical","label":"Cr?tica"}]'::jsonb,false,NULL,NULL,20),
    ('rede_cabeamento','asset_type','Equipamento afetado','Tipo de equipamento ou ambiente relacionado ao chamado.','choice','[{"value":"pc","label":"PC"},{"value":"notebook","label":"Notebook"},{"value":"rede","label":"Rede"},{"value":"cftv","label":"CFTV"},{"value":"impressora","label":"Impressora"},{"value":"energia","label":"Energia"},{"value":"outro","label":"Outro"}]'::jsonb,false,NULL,NULL,30),
    ('rede_cabeamento','modality_note','Observa??o de modalidade','Informe se h? restri??o para remoto, presencial, hor?rio ou acesso.','text','[]'::jsonb,false,NULL,NULL,40),
    ('rede_cabeamento','address','Endere?o do atendimento','Obrigat?rio quando o atendimento for presencial.','text','[]'::jsonb,true,'modality','onsite',50),
    ('rede_cabeamento','attachments','Fotos/evid?ncias iniciais','Fotos, prints, nota fiscal ou v?deos curtos que ajudem o diagn?stico.','attachment','[]'::jsonb,false,NULL,NULL,90),
    ('rede_cabeamento','points_count','Quantidade de pontos','N?mero aproximado de pontos/cabos.','number','[]'::jsonb,false,NULL,NULL,60),
    ('rede_cabeamento','cable_distance','Metragem estimada','Metragem aproximada de cabo, se souber.','number','[]'::jsonb,false,NULL,NULL,70),
    ('rede_wifi','description','O que est? acontecendo','Descreva o sintoma principal com as suas palavras.','multiline','[]'::jsonb,true,NULL,NULL,10),
    ('rede_wifi','urgency','Urg?ncia','Impacto operacional do problema.','choice','[{"value":"low","label":"Baixa"},{"value":"normal","label":"Normal"},{"value":"high","label":"Alta"},{"value":"critical","label":"Cr?tica"}]'::jsonb,false,NULL,NULL,20),
    ('rede_wifi','asset_type','Equipamento afetado','Tipo de equipamento ou ambiente relacionado ao chamado.','choice','[{"value":"pc","label":"PC"},{"value":"notebook","label":"Notebook"},{"value":"rede","label":"Rede"},{"value":"cftv","label":"CFTV"},{"value":"impressora","label":"Impressora"},{"value":"energia","label":"Energia"},{"value":"outro","label":"Outro"}]'::jsonb,false,NULL,NULL,30),
    ('rede_wifi','modality_note','Observa??o de modalidade','Informe se h? restri??o para remoto, presencial, hor?rio ou acesso.','text','[]'::jsonb,false,NULL,NULL,40),
    ('rede_wifi','address','Endere?o do atendimento','Obrigat?rio quando o atendimento for presencial.','text','[]'::jsonb,true,'modality','onsite',50),
    ('rede_wifi','attachments','Fotos/evid?ncias iniciais','Fotos, prints, nota fiscal ou v?deos curtos que ajudem o diagn?stico.','attachment','[]'::jsonb,false,NULL,NULL,90),
    ('rede_wifi','coverage_area','?rea de cobertura','Ambiente, pavimentos, paredes e locais sem sinal.','multiline','[]'::jsonb,false,NULL,NULL,60),
    ('rede_roteador_firewall','description','O que est? acontecendo','Descreva o sintoma principal com as suas palavras.','multiline','[]'::jsonb,true,NULL,NULL,10),
    ('rede_roteador_firewall','urgency','Urg?ncia','Impacto operacional do problema.','choice','[{"value":"low","label":"Baixa"},{"value":"normal","label":"Normal"},{"value":"high","label":"Alta"},{"value":"critical","label":"Cr?tica"}]'::jsonb,false,NULL,NULL,20),
    ('rede_roteador_firewall','asset_type','Equipamento afetado','Tipo de equipamento ou ambiente relacionado ao chamado.','choice','[{"value":"pc","label":"PC"},{"value":"notebook","label":"Notebook"},{"value":"rede","label":"Rede"},{"value":"cftv","label":"CFTV"},{"value":"impressora","label":"Impressora"},{"value":"energia","label":"Energia"},{"value":"outro","label":"Outro"}]'::jsonb,false,NULL,NULL,30),
    ('rede_roteador_firewall','modality_note','Observa??o de modalidade','Informe se h? restri??o para remoto, presencial, hor?rio ou acesso.','text','[]'::jsonb,false,NULL,NULL,40),
    ('rede_roteador_firewall','address','Endere?o do atendimento','Obrigat?rio quando o atendimento for presencial.','text','[]'::jsonb,true,'modality','onsite',50),
    ('rede_roteador_firewall','attachments','Fotos/evid?ncias iniciais','Fotos, prints, nota fiscal ou v?deos curtos que ajudem o diagn?stico.','attachment','[]'::jsonb,false,NULL,NULL,90),
    ('rede_rack_switch','description','O que est? acontecendo','Descreva o sintoma principal com as suas palavras.','multiline','[]'::jsonb,true,NULL,NULL,10),
    ('rede_rack_switch','urgency','Urg?ncia','Impacto operacional do problema.','choice','[{"value":"low","label":"Baixa"},{"value":"normal","label":"Normal"},{"value":"high","label":"Alta"},{"value":"critical","label":"Cr?tica"}]'::jsonb,false,NULL,NULL,20),
    ('rede_rack_switch','asset_type','Equipamento afetado','Tipo de equipamento ou ambiente relacionado ao chamado.','choice','[{"value":"pc","label":"PC"},{"value":"notebook","label":"Notebook"},{"value":"rede","label":"Rede"},{"value":"cftv","label":"CFTV"},{"value":"impressora","label":"Impressora"},{"value":"energia","label":"Energia"},{"value":"outro","label":"Outro"}]'::jsonb,false,NULL,NULL,30),
    ('rede_rack_switch','modality_note','Observa??o de modalidade','Informe se h? restri??o para remoto, presencial, hor?rio ou acesso.','text','[]'::jsonb,false,NULL,NULL,40),
    ('rede_rack_switch','address','Endere?o do atendimento','Obrigat?rio quando o atendimento for presencial.','text','[]'::jsonb,true,'modality','onsite',50),
    ('rede_rack_switch','attachments','Fotos/evid?ncias iniciais','Fotos, prints, nota fiscal ou v?deos curtos que ajudem o diagn?stico.','attachment','[]'::jsonb,false,NULL,NULL,90),
    ('cftv_camera','description','O que est? acontecendo','Descreva o sintoma principal com as suas palavras.','multiline','[]'::jsonb,true,NULL,NULL,10),
    ('cftv_camera','urgency','Urg?ncia','Impacto operacional do problema.','choice','[{"value":"low","label":"Baixa"},{"value":"normal","label":"Normal"},{"value":"high","label":"Alta"},{"value":"critical","label":"Cr?tica"}]'::jsonb,false,NULL,NULL,20),
    ('cftv_camera','asset_type','Equipamento afetado','Tipo de equipamento ou ambiente relacionado ao chamado.','choice','[{"value":"pc","label":"PC"},{"value":"notebook","label":"Notebook"},{"value":"rede","label":"Rede"},{"value":"cftv","label":"CFTV"},{"value":"impressora","label":"Impressora"},{"value":"energia","label":"Energia"},{"value":"outro","label":"Outro"}]'::jsonb,false,NULL,NULL,30),
    ('cftv_camera','modality_note','Observa??o de modalidade','Informe se h? restri??o para remoto, presencial, hor?rio ou acesso.','text','[]'::jsonb,false,NULL,NULL,40),
    ('cftv_camera','address','Endere?o do atendimento','Obrigat?rio quando o atendimento for presencial.','text','[]'::jsonb,true,'modality','onsite',50),
    ('cftv_camera','attachments','Fotos/evid?ncias iniciais','Fotos, prints, nota fiscal ou v?deos curtos que ajudem o diagn?stico.','attachment','[]'::jsonb,false,NULL,NULL,90),
    ('cftv_camera','camera_count','Quantidade de c?meras','N?mero de c?meras envolvidas.','number','[]'::jsonb,false,NULL,NULL,60),
    ('cftv_camera','camera_type','Tipo de c?mera','Anal?gica, IP, dome, bullet ou desconhecida.','choice','[{"value":"analog","label":"Anal?gica"},{"value":"ip","label":"IP"},{"value":"dome","label":"Dome"},{"value":"bullet","label":"Bullet"},{"value":"unknown","label":"N?o sei"}]'::jsonb,false,NULL,NULL,70),
    ('cftv_gravador','description','O que est? acontecendo','Descreva o sintoma principal com as suas palavras.','multiline','[]'::jsonb,true,NULL,NULL,10),
    ('cftv_gravador','urgency','Urg?ncia','Impacto operacional do problema.','choice','[{"value":"low","label":"Baixa"},{"value":"normal","label":"Normal"},{"value":"high","label":"Alta"},{"value":"critical","label":"Cr?tica"}]'::jsonb,false,NULL,NULL,20),
    ('cftv_gravador','asset_type','Equipamento afetado','Tipo de equipamento ou ambiente relacionado ao chamado.','choice','[{"value":"pc","label":"PC"},{"value":"notebook","label":"Notebook"},{"value":"rede","label":"Rede"},{"value":"cftv","label":"CFTV"},{"value":"impressora","label":"Impressora"},{"value":"energia","label":"Energia"},{"value":"outro","label":"Outro"}]'::jsonb,false,NULL,NULL,30),
    ('cftv_gravador','modality_note','Observa??o de modalidade','Informe se h? restri??o para remoto, presencial, hor?rio ou acesso.','text','[]'::jsonb,false,NULL,NULL,40),
    ('cftv_gravador','address','Endere?o do atendimento','Obrigat?rio quando o atendimento for presencial.','text','[]'::jsonb,true,'modality','onsite',50),
    ('cftv_gravador','attachments','Fotos/evid?ncias iniciais','Fotos, prints, nota fiscal ou v?deos curtos que ajudem o diagn?stico.','attachment','[]'::jsonb,false,NULL,NULL,90),
    ('cftv_gravador','channels_count','Canais do gravador','Quantidade de canais do DVR/NVR.','choice','[{"value":"4","label":"4 canais"},{"value":"8","label":"8 canais"},{"value":"16","label":"16 canais"},{"value":"32","label":"32 canais"},{"value":"unknown","label":"N?o sei"}]'::jsonb,false,NULL,NULL,60),
    ('cftv_acesso_remoto','description','O que est? acontecendo','Descreva o sintoma principal com as suas palavras.','multiline','[]'::jsonb,true,NULL,NULL,10),
    ('cftv_acesso_remoto','urgency','Urg?ncia','Impacto operacional do problema.','choice','[{"value":"low","label":"Baixa"},{"value":"normal","label":"Normal"},{"value":"high","label":"Alta"},{"value":"critical","label":"Cr?tica"}]'::jsonb,false,NULL,NULL,20),
    ('cftv_acesso_remoto','asset_type','Equipamento afetado','Tipo de equipamento ou ambiente relacionado ao chamado.','choice','[{"value":"pc","label":"PC"},{"value":"notebook","label":"Notebook"},{"value":"rede","label":"Rede"},{"value":"cftv","label":"CFTV"},{"value":"impressora","label":"Impressora"},{"value":"energia","label":"Energia"},{"value":"outro","label":"Outro"}]'::jsonb,false,NULL,NULL,30),
    ('cftv_acesso_remoto','modality_note','Observa??o de modalidade','Informe se h? restri??o para remoto, presencial, hor?rio ou acesso.','text','[]'::jsonb,false,NULL,NULL,40),
    ('cftv_acesso_remoto','address','Endere?o do atendimento','Obrigat?rio quando o atendimento for presencial.','text','[]'::jsonb,true,'modality','onsite',50),
    ('cftv_acesso_remoto','attachments','Fotos/evid?ncias iniciais','Fotos, prints, nota fiscal ou v?deos curtos que ajudem o diagn?stico.','attachment','[]'::jsonb,false,NULL,NULL,90),
    ('energia_nobreak_bateria','description','O que est? acontecendo','Descreva o sintoma principal com as suas palavras.','multiline','[]'::jsonb,true,NULL,NULL,10),
    ('energia_nobreak_bateria','urgency','Urg?ncia','Impacto operacional do problema.','choice','[{"value":"low","label":"Baixa"},{"value":"normal","label":"Normal"},{"value":"high","label":"Alta"},{"value":"critical","label":"Cr?tica"}]'::jsonb,false,NULL,NULL,20),
    ('energia_nobreak_bateria','asset_type','Equipamento afetado','Tipo de equipamento ou ambiente relacionado ao chamado.','choice','[{"value":"pc","label":"PC"},{"value":"notebook","label":"Notebook"},{"value":"rede","label":"Rede"},{"value":"cftv","label":"CFTV"},{"value":"impressora","label":"Impressora"},{"value":"energia","label":"Energia"},{"value":"outro","label":"Outro"}]'::jsonb,false,NULL,NULL,30),
    ('energia_nobreak_bateria','modality_note','Observa??o de modalidade','Informe se h? restri??o para remoto, presencial, hor?rio ou acesso.','text','[]'::jsonb,false,NULL,NULL,40),
    ('energia_nobreak_bateria','address','Endere?o do atendimento','Obrigat?rio quando o atendimento for presencial.','text','[]'::jsonb,true,'modality','onsite',50),
    ('energia_nobreak_bateria','attachments','Fotos/evid?ncias iniciais','Fotos, prints, nota fiscal ou v?deos curtos que ajudem o diagn?stico.','attachment','[]'::jsonb,false,NULL,NULL,90),
    ('energia_nobreak_bateria','battery_model','Modelo/capacidade da bateria','Ex.: 12 V 7 Ah, 12 V 9 Ah, desconhecido.','text','[]'::jsonb,false,NULL,NULL,60),
    ('energia_tomada_protecao','description','O que est? acontecendo','Descreva o sintoma principal com as suas palavras.','multiline','[]'::jsonb,true,NULL,NULL,10),
    ('energia_tomada_protecao','urgency','Urg?ncia','Impacto operacional do problema.','choice','[{"value":"low","label":"Baixa"},{"value":"normal","label":"Normal"},{"value":"high","label":"Alta"},{"value":"critical","label":"Cr?tica"}]'::jsonb,false,NULL,NULL,20),
    ('energia_tomada_protecao','asset_type','Equipamento afetado','Tipo de equipamento ou ambiente relacionado ao chamado.','choice','[{"value":"pc","label":"PC"},{"value":"notebook","label":"Notebook"},{"value":"rede","label":"Rede"},{"value":"cftv","label":"CFTV"},{"value":"impressora","label":"Impressora"},{"value":"energia","label":"Energia"},{"value":"outro","label":"Outro"}]'::jsonb,false,NULL,NULL,30),
    ('energia_tomada_protecao','modality_note','Observa??o de modalidade','Informe se h? restri??o para remoto, presencial, hor?rio ou acesso.','text','[]'::jsonb,false,NULL,NULL,40),
    ('energia_tomada_protecao','address','Endere?o do atendimento','Obrigat?rio quando o atendimento for presencial.','text','[]'::jsonb,true,'modality','onsite',50),
    ('energia_tomada_protecao','attachments','Fotos/evid?ncias iniciais','Fotos, prints, nota fiscal ou v?deos curtos que ajudem o diagn?stico.','attachment','[]'::jsonb,false,NULL,NULL,90),
    ('atendimento_avulso_orientacao','description','O que est? acontecendo','Descreva o sintoma principal com as suas palavras.','multiline','[]'::jsonb,true,NULL,NULL,10),
    ('atendimento_avulso_orientacao','urgency','Urg?ncia','Impacto operacional do problema.','choice','[{"value":"low","label":"Baixa"},{"value":"normal","label":"Normal"},{"value":"high","label":"Alta"},{"value":"critical","label":"Cr?tica"}]'::jsonb,false,NULL,NULL,20),
    ('atendimento_avulso_orientacao','asset_type','Equipamento afetado','Tipo de equipamento ou ambiente relacionado ao chamado.','choice','[{"value":"pc","label":"PC"},{"value":"notebook","label":"Notebook"},{"value":"rede","label":"Rede"},{"value":"cftv","label":"CFTV"},{"value":"impressora","label":"Impressora"},{"value":"energia","label":"Energia"},{"value":"outro","label":"Outro"}]'::jsonb,false,NULL,NULL,30),
    ('atendimento_avulso_orientacao','modality_note','Observa??o de modalidade','Informe se h? restri??o para remoto, presencial, hor?rio ou acesso.','text','[]'::jsonb,false,NULL,NULL,40),
    ('atendimento_avulso_orientacao','address','Endere?o do atendimento','Obrigat?rio quando o atendimento for presencial.','text','[]'::jsonb,true,'modality','onsite',50),
    ('atendimento_avulso_orientacao','attachments','Fotos/evid?ncias iniciais','Fotos, prints, nota fiscal ou v?deos curtos que ajudem o diagn?stico.','attachment','[]'::jsonb,false,NULL,NULL,90),
    ('instalacao_postos_loja','description','O que est? acontecendo','Descreva o sintoma principal com as suas palavras.','multiline','[]'::jsonb,true,NULL,NULL,10),
    ('instalacao_postos_loja','urgency','Urg?ncia','Impacto operacional do problema.','choice','[{"value":"low","label":"Baixa"},{"value":"normal","label":"Normal"},{"value":"high","label":"Alta"},{"value":"critical","label":"Cr?tica"}]'::jsonb,false,NULL,NULL,20),
    ('instalacao_postos_loja','asset_type','Equipamento afetado','Tipo de equipamento ou ambiente relacionado ao chamado.','choice','[{"value":"pc","label":"PC"},{"value":"notebook","label":"Notebook"},{"value":"rede","label":"Rede"},{"value":"cftv","label":"CFTV"},{"value":"impressora","label":"Impressora"},{"value":"energia","label":"Energia"},{"value":"outro","label":"Outro"}]'::jsonb,false,NULL,NULL,30),
    ('instalacao_postos_loja','modality_note','Observa??o de modalidade','Informe se h? restri??o para remoto, presencial, hor?rio ou acesso.','text','[]'::jsonb,false,NULL,NULL,40),
    ('instalacao_postos_loja','address','Endere?o do atendimento','Obrigat?rio quando o atendimento for presencial.','text','[]'::jsonb,true,'modality','onsite',50),
    ('instalacao_postos_loja','attachments','Fotos/evid?ncias iniciais','Fotos, prints, nota fiscal ou v?deos curtos que ajudem o diagn?stico.','attachment','[]'::jsonb,false,NULL,NULL,90),
    ('manutencao_preventiva_contrato','description','O que est? acontecendo','Descreva o sintoma principal com as suas palavras.','multiline','[]'::jsonb,true,NULL,NULL,10),
    ('manutencao_preventiva_contrato','urgency','Urg?ncia','Impacto operacional do problema.','choice','[{"value":"low","label":"Baixa"},{"value":"normal","label":"Normal"},{"value":"high","label":"Alta"},{"value":"critical","label":"Cr?tica"}]'::jsonb,false,NULL,NULL,20),
    ('manutencao_preventiva_contrato','asset_type','Equipamento afetado','Tipo de equipamento ou ambiente relacionado ao chamado.','choice','[{"value":"pc","label":"PC"},{"value":"notebook","label":"Notebook"},{"value":"rede","label":"Rede"},{"value":"cftv","label":"CFTV"},{"value":"impressora","label":"Impressora"},{"value":"energia","label":"Energia"},{"value":"outro","label":"Outro"}]'::jsonb,false,NULL,NULL,30),
    ('manutencao_preventiva_contrato','modality_note','Observa??o de modalidade','Informe se h? restri??o para remoto, presencial, hor?rio ou acesso.','text','[]'::jsonb,false,NULL,NULL,40),
    ('manutencao_preventiva_contrato','address','Endere?o do atendimento','Obrigat?rio quando o atendimento for presencial.','text','[]'::jsonb,true,'modality','onsite',50),
    ('manutencao_preventiva_contrato','attachments','Fotos/evid?ncias iniciais','Fotos, prints, nota fiscal ou v?deos curtos que ajudem o diagn?stico.','attachment','[]'::jsonb,false,NULL,NULL,90)
ON CONFLICT (type_key,field_key) DO UPDATE SET
    label=excluded.label,
    help=excluded.help,
    kind=excluded.kind,
    options=excluded.options,
    required=excluded.required,
    depends_on=excluded.depends_on,
    depends_value=excluded.depends_value,
    position=excluded.position,
    active=true;

UPDATE service_catalog AS service
SET ticket_type_key = mapping.ticket_type_key, updated_at = now()
FROM (VALUES
    ('software_diagnostico_profundo','lentidao_intermitente'),
    ('software_remocao_malware','malware_seguranca'),
    ('software_otimizacao_inicializacao','lentidao_intermitente'),
    ('software_reinstalacao_driver','driver_firmware_bios'),
    ('software_configuracao_backup','backup_migracao_dados'),
    ('software_formatacao_windows','manutencao_sistema_operacional'),
    ('software_instalacao_linux','manutencao_sistema_operacional'),
    ('software_dual_boot','manutencao_sistema_operacional'),
    ('software_migracao_perfil','backup_migracao_dados'),
    ('software_recuperacao_sistema','manutencao_sistema_operacional'),
    ('software_limpeza_temporarios','lentidao_intermitente'),
    ('software_office_email','certificado_erp_email'),
    ('software_antivirus_edr','malware_seguranca'),
    ('software_atualizacao_bios','driver_firmware_bios'),
    ('software_virtualizacao','instalacao_programas'),
    ('software_vpn_acesso_remoto','rede_roteador_firewall'),
    ('software_erp_certificado','certificado_erp_email'),
    ('hardware_diagnostico_bancada','diagnostico_geral'),
    ('hardware_limpeza_preventiva','limpeza_termica'),
    ('hardware_troca_memoria','troca_memoria'),
    ('hardware_troca_ssd_hd','troca_armazenamento'),
    ('hardware_troca_fonte','troca_fonte_energia_pc'),
    ('hardware_montagem_pc','hardware_desktop'),
    ('hardware_upgrade_pc','hardware_desktop'),
    ('hardware_troca_placa_mae','troca_placa_processador'),
    ('hardware_troca_processador','troca_placa_processador'),
    ('hardware_troca_cooler','limpeza_termica'),
    ('hardware_troca_tela_note','hardware_notebook'),
    ('hardware_troca_teclado_note','hardware_notebook'),
    ('hardware_troca_bateria_note','hardware_notebook'),
    ('hardware_reparo_conector_dc','hardware_notebook'),
    ('hardware_diagnostico_intermitencia','diagnostico_geral'),
    ('rede_crimpagem_ponto','rede_cabeamento'),
    ('rede_configuracao_roteador','rede_roteador_firewall'),
    ('rede_passagem_cabo','rede_cabeamento'),
    ('rede_site_survey_wifi','rede_wifi'),
    ('rede_instalacao_rack','rede_rack_switch'),
    ('rede_patch_panel','rede_rack_switch'),
    ('rede_vlan_basica','rede_roteador_firewall'),
    ('rede_firewall_basico','rede_roteador_firewall'),
    ('rede_ponto_adicional','rede_cabeamento'),
    ('rede_mesh_wifi','rede_wifi'),
    ('cftv_substituir_camera','cftv_camera'),
    ('cftv_configurar_nvr_dvr','cftv_gravador'),
    ('cftv_instalacao_camera','cftv_camera'),
    ('cftv_instalacao_dvr_nvr','cftv_gravador'),
    ('cftv_acesso_remoto','cftv_acesso_remoto'),
    ('cftv_manutencao_imagem','cftv_camera'),
    ('cftv_troca_hd_gravador','cftv_gravador'),
    ('impressora_instalacao','impressora_scanner'),
    ('impressora_manutencao_fila','impressora_scanner'),
    ('impressora_rede_scan','impressora_scanner'),
    ('periferico_instalacao_webcam','perifericos_usb_audio_video'),
    ('dados_clonagem_disco','backup_migracao_dados'),
    ('dados_recuperacao_basica','backup_migracao_dados'),
    ('energia_teste_nobreak','energia_nobreak_bateria'),
    ('energia_troca_bateria_nobreak','energia_nobreak_bateria'),
    ('energia_diagnostico_tomada','energia_tomada_protecao')
) AS mapping(service_key,ticket_type_key)
WHERE service.key = mapping.service_key;
