-- TGDesk: rela??o muitos-para-muitos entre tipo de chamado e servi?os poss?veis.
-- Mant?m service_catalog.ticket_type_key como tipo principal e permite sugerir o mesmo servi?o em outros tipos.

CREATE TABLE IF NOT EXISTS ticket_type_service_options (
    type_key      TEXT NOT NULL REFERENCES ticket_types(key) ON UPDATE CASCADE ON DELETE CASCADE,
    service_key   TEXT NOT NULL REFERENCES service_catalog(key) ON UPDATE CASCADE ON DELETE CASCADE,
    relation_kind TEXT NOT NULL DEFAULT 'possible' CHECK (relation_kind IN ('possible','recommended','required')),
    default_pick  BOOLEAN NOT NULL DEFAULT false,
    position      INTEGER NOT NULL DEFAULT 100,
    active        BOOLEAN NOT NULL DEFAULT true,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY(type_key, service_key)
);

CREATE INDEX IF NOT EXISTS ticket_type_service_options_pick_idx
    ON ticket_type_service_options(type_key, active, position, service_key);

INSERT INTO ticket_type_service_options(type_key,service_key,relation_kind,default_pick,position) VALUES
    ('diagnostico_geral','software_diagnostico_profundo','possible',true,10),
    ('lentidao_intermitente','software_diagnostico_profundo','possible',false,20),
    ('manutencao_sistema_operacional','software_diagnostico_profundo','possible',false,30),
    ('diagnostico_geral','hardware_diagnostico_bancada','possible',true,10),
    ('hardware_desktop','hardware_diagnostico_bancada','possible',false,20),
    ('hardware_notebook','hardware_diagnostico_bancada','possible',false,30),
    ('diagnostico_geral','hardware_diagnostico_intermitencia','possible',true,10),
    ('lentidao_intermitente','hardware_diagnostico_intermitencia','possible',false,20),
    ('hardware_desktop','hardware_diagnostico_intermitencia','possible',false,30),
    ('hardware_notebook','hardware_diagnostico_intermitencia','possible',false,40),
    ('driver_firmware_bios','software_reinstalacao_driver','possible',true,10),
    ('perifericos_usb_audio_video','software_reinstalacao_driver','possible',false,20),
    ('impressora_scanner','software_reinstalacao_driver','possible',false,30),
    ('rede_diagnostico','software_reinstalacao_driver','possible',false,40),
    ('driver_firmware_bios','software_atualizacao_bios','possible',true,10),
    ('hardware_desktop','software_atualizacao_bios','possible',false,20),
    ('hardware_notebook','software_atualizacao_bios','possible',false,30),
    ('rede_roteador_firewall','software_vpn_acesso_remoto','possible',true,10),
    ('manutencao_sistema_operacional','software_vpn_acesso_remoto','possible',false,20),
    ('certificado_erp_email','software_vpn_acesso_remoto','possible',false,30),
    ('certificado_erp_email','software_erp_certificado','possible',true,10),
    ('instalacao_programas','software_erp_certificado','possible',false,20),
    ('certificado_erp_email','software_office_email','possible',true,10),
    ('instalacao_programas','software_office_email','possible',false,20),
    ('malware_seguranca','software_antivirus_edr','possible',true,10),
    ('manutencao_sistema_operacional','software_antivirus_edr','possible',false,20),
    ('lentidao_intermitente','software_antivirus_edr','possible',false,30),
    ('lentidao_intermitente','software_otimizacao_inicializacao','possible',true,10),
    ('manutencao_sistema_operacional','software_otimizacao_inicializacao','possible',false,20),
    ('manutencao_sistema_operacional','software_recuperacao_sistema','possible',true,10),
    ('backup_migracao_dados','software_recuperacao_sistema','possible',false,20),
    ('backup_migracao_dados','software_migracao_perfil','possible',true,10),
    ('manutencao_sistema_operacional','software_migracao_perfil','possible',false,20),
    ('backup_migracao_dados','dados_clonagem_disco','possible',true,10),
    ('troca_armazenamento','dados_clonagem_disco','possible',false,20),
    ('backup_migracao_dados','dados_recuperacao_basica','possible',true,10),
    ('troca_armazenamento','dados_recuperacao_basica','possible',false,20),
    ('troca_memoria','hardware_troca_memoria','possible',true,10),
    ('hardware_desktop','hardware_troca_memoria','possible',false,20),
    ('hardware_notebook','hardware_troca_memoria','possible',false,30),
    ('troca_armazenamento','hardware_troca_ssd_hd','possible',true,10),
    ('hardware_desktop','hardware_troca_ssd_hd','possible',false,20),
    ('hardware_notebook','hardware_troca_ssd_hd','possible',false,30),
    ('troca_fonte_energia_pc','hardware_troca_fonte','possible',true,10),
    ('hardware_desktop','hardware_troca_fonte','possible',false,20),
    ('energia_tomada_protecao','hardware_troca_fonte','possible',false,30),
    ('troca_placa_processador','hardware_troca_placa_mae','possible',true,10),
    ('hardware_desktop','hardware_troca_placa_mae','possible',false,20),
    ('troca_placa_processador','hardware_troca_processador','possible',true,10),
    ('hardware_desktop','hardware_troca_processador','possible',false,20),
    ('limpeza_termica','hardware_troca_cooler','possible',true,10),
    ('hardware_desktop','hardware_troca_cooler','possible',false,20),
    ('hardware_notebook','hardware_troca_cooler','possible',false,30),
    ('limpeza_termica','hardware_limpeza_preventiva','possible',true,10),
    ('hardware_desktop','hardware_limpeza_preventiva','possible',false,20),
    ('hardware_notebook','hardware_limpeza_preventiva','possible',false,30),
    ('hardware_desktop','hardware_montagem_pc','possible',true,10),
    ('troca_placa_processador','hardware_montagem_pc','possible',false,20),
    ('troca_memoria','hardware_montagem_pc','possible',false,30),
    ('troca_armazenamento','hardware_montagem_pc','possible',false,40),
    ('hardware_desktop','hardware_upgrade_pc','possible',true,10),
    ('troca_memoria','hardware_upgrade_pc','possible',false,20),
    ('troca_armazenamento','hardware_upgrade_pc','possible',false,30),
    ('troca_placa_processador','hardware_upgrade_pc','possible',false,40),
    ('hardware_notebook','hardware_troca_tela_note','possible',true,10),
    ('hardware_notebook','hardware_troca_teclado_note','possible',true,10),
    ('hardware_notebook','hardware_troca_bateria_note','possible',true,10),
    ('energia_nobreak_bateria','hardware_troca_bateria_note','possible',false,20),
    ('hardware_notebook','hardware_reparo_conector_dc','possible',true,10),
    ('energia_tomada_protecao','hardware_reparo_conector_dc','possible',false,20),
    ('rede_cabeamento','rede_crimpagem_ponto','possible',true,10),
    ('rede_diagnostico','rede_crimpagem_ponto','possible',false,20),
    ('rede_cabeamento','rede_passagem_cabo','possible',true,10),
    ('rede_cabeamento','rede_ponto_adicional','possible',true,10),
    ('rede_rack_switch','rede_ponto_adicional','possible',false,20),
    ('rede_roteador_firewall','rede_configuracao_roteador','possible',true,10),
    ('rede_wifi','rede_configuracao_roteador','possible',false,20),
    ('rede_diagnostico','rede_configuracao_roteador','possible',false,30),
    ('rede_wifi','rede_site_survey_wifi','possible',true,10),
    ('rede_diagnostico','rede_site_survey_wifi','possible',false,20),
    ('rede_wifi','rede_mesh_wifi','possible',true,10),
    ('rede_roteador_firewall','rede_vlan_basica','possible',true,10),
    ('rede_rack_switch','rede_vlan_basica','possible',false,20),
    ('rede_roteador_firewall','rede_firewall_basico','possible',true,10),
    ('rede_diagnostico','rede_firewall_basico','possible',false,20),
    ('rede_rack_switch','rede_instalacao_rack','possible',true,10),
    ('rede_cabeamento','rede_instalacao_rack','possible',false,20),
    ('rede_rack_switch','rede_patch_panel','possible',true,10),
    ('rede_cabeamento','rede_patch_panel','possible',false,20),
    ('cftv_camera','cftv_substituir_camera','possible',true,10),
    ('cftv_gravador','cftv_substituir_camera','possible',false,20),
    ('cftv_camera','cftv_instalacao_camera','possible',true,10),
    ('rede_cabeamento','cftv_instalacao_camera','possible',false,20),
    ('cftv_gravador','cftv_configurar_nvr_dvr','possible',true,10),
    ('cftv_acesso_remoto','cftv_configurar_nvr_dvr','possible',false,20),
    ('cftv_gravador','cftv_instalacao_dvr_nvr','possible',true,10),
    ('cftv_camera','cftv_instalacao_dvr_nvr','possible',false,20),
    ('cftv_acesso_remoto','cftv_instalacao_dvr_nvr','possible',false,30),
    ('cftv_acesso_remoto','cftv_acesso_remoto','possible',true,10),
    ('cftv_gravador','cftv_acesso_remoto','possible',false,20),
    ('rede_roteador_firewall','cftv_acesso_remoto','possible',false,30),
    ('cftv_camera','cftv_manutencao_imagem','possible',true,10),
    ('cftv_gravador','cftv_manutencao_imagem','possible',false,20),
    ('rede_cabeamento','cftv_manutencao_imagem','possible',false,30),
    ('cftv_gravador','cftv_troca_hd_gravador','possible',true,10),
    ('troca_armazenamento','cftv_troca_hd_gravador','possible',false,20),
    ('impressora_scanner','impressora_instalacao','possible',true,10),
    ('rede_wifi','impressora_instalacao','possible',false,20),
    ('rede_cabeamento','impressora_instalacao','possible',false,30),
    ('impressora_scanner','impressora_manutencao_fila','possible',true,10),
    ('manutencao_sistema_operacional','impressora_manutencao_fila','possible',false,20),
    ('impressora_scanner','impressora_rede_scan','possible',true,10),
    ('rede_roteador_firewall','impressora_rede_scan','possible',false,20),
    ('perifericos_usb_audio_video','periferico_instalacao_webcam','possible',true,10),
    ('driver_firmware_bios','periferico_instalacao_webcam','possible',false,20),
    ('energia_nobreak_bateria','energia_teste_nobreak','possible',true,10),
    ('energia_tomada_protecao','energia_teste_nobreak','possible',false,20),
    ('energia_nobreak_bateria','energia_troca_bateria_nobreak','possible',true,10),
    ('energia_tomada_protecao','energia_diagnostico_tomada','possible',true,10),
    ('troca_fonte_energia_pc','energia_diagnostico_tomada','possible',false,20)
ON CONFLICT (type_key,service_key) DO UPDATE SET
    relation_kind=excluded.relation_kind,
    default_pick=excluded.default_pick,
    position=excluded.position,
    active=true,
    updated_at=now();

INSERT INTO ticket_type_service_options(type_key,service_key,relation_kind,default_pick,position)
SELECT ticket_type_key, key, 'possible', true, 5
FROM service_catalog
WHERE ticket_type_key IS NOT NULL
ON CONFLICT (type_key,service_key) DO NOTHING;
